# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\modules\ui\export\ui_export.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setEnabled(True)
        TabWidget.resize(800, 850)
        TabWidget.setMinimumSize(QtCore.QSize(800, 850))
        TabWidget.setMaximumSize(QtCore.QSize(800, 850))
        TabWidget.setWindowTitle("Isogeo To Office")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.setWindowIcon(icon)
        TabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        TabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        TabWidget.setTabBarAutoHide(False)
        self.Export = QtWidgets.QWidget()
        self.Export.setObjectName("Export")
        self.Filters = QtWidgets.QGroupBox(self.Export)
        self.Filters.setGeometry(QtCore.QRect(20, 150, 751, 271))
        self.Filters.setObjectName("Filters")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Filters)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 731, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.lyt_advc_search = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.lyt_advc_search.setContentsMargins(0, 0, 0, 0)
        self.lyt_advc_search.setObjectName("lyt_advc_search")
        self.lyt_vert_filters_left = QtWidgets.QVBoxLayout()
        self.lyt_vert_filters_left.setObjectName("lyt_vert_filters_left")
        self.lyt_vert_share = QtWidgets.QVBoxLayout()
        self.lyt_vert_share.setObjectName("lyt_vert_share")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ico_share = QtWidgets.QLabel(self.layoutWidget_2)
        self.ico_share.setMaximumSize(QtCore.QSize(18, 18))
        self.ico_share.setText("")
        self.ico_share.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/map.svg"))
        self.ico_share.setScaledContents(True)
        self.ico_share.setObjectName("ico_share")
        self.horizontalLayout.addWidget(self.ico_share)
        self.lbl_share = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_share.setFont(font)
        self.lbl_share.setObjectName("lbl_share")
        self.horizontalLayout.addWidget(self.lbl_share)
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lyt_vert_share.addLayout(self.horizontalLayout)
        self.cbb_share = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cbb_share.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_share.setObjectName("cbb_share")
        self.lyt_vert_share.addWidget(self.cbb_share)
        self.lyt_vert_filters_left.addLayout(self.lyt_vert_share)
        self.lyt_vert_filter_owner = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_owner.setObjectName("lyt_vert_filter_owner")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ico_owner = QtWidgets.QLabel(self.layoutWidget_2)
        self.ico_owner.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ico_owner.setFont(font)
        self.ico_owner.setText("")
        self.ico_owner.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/search/cube.svg"))
        self.ico_owner.setScaledContents(True)
        self.ico_owner.setObjectName("ico_owner")
        self.horizontalLayout_3.addWidget(self.ico_owner)
        self.lbl_owner = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_owner.setFont(font)
        self.lbl_owner.setObjectName("lbl_owner")
        self.horizontalLayout_3.addWidget(self.lbl_owner)
        spacerItem1 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lyt_vert_filter_owner.addLayout(self.horizontalLayout_3)
        self.cbb_format = QtWidgets.QComboBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_format.sizePolicy().hasHeightForWidth())
        self.cbb_format.setSizePolicy(sizePolicy)
        self.cbb_format.setMinimumSize(QtCore.QSize(30, 0))
        self.cbb_format.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbb_format.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_format.setObjectName("cbb_format")
        self.lyt_vert_filter_owner.addWidget(self.cbb_format)
        self.lyt_vert_filters_left.addLayout(self.lyt_vert_filter_owner)
        self.lyt_advc_search.addLayout(self.lyt_vert_filters_left)
        self.lyt_vert_filters_right = QtWidgets.QVBoxLayout()
        self.lyt_vert_filters_right.setObjectName("lyt_vert_filters_right")
        self.lyt_vert_filter_type = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_type.setObjectName("lyt_vert_filter_type")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ico_type = QtWidgets.QLabel(self.layoutWidget_2)
        self.ico_type.setMaximumSize(QtCore.QSize(18, 18))
        self.ico_type.setText("")
        self.ico_type.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/search/asterisk.svg"))
        self.ico_type.setScaledContents(True)
        self.ico_type.setObjectName("ico_type")
        self.horizontalLayout_2.addWidget(self.ico_type)
        self.lbl_type = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_type.setFont(font)
        self.lbl_type.setObjectName("lbl_type")
        self.horizontalLayout_2.addWidget(self.lbl_type)
        spacerItem2 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lyt_vert_filter_type.addLayout(self.horizontalLayout_2)
        self.cbb_type = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cbb_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_type.setObjectName("cbb_type")
        self.lyt_vert_filter_type.addWidget(self.cbb_type)
        self.lyt_vert_filters_right.addLayout(self.lyt_vert_filter_type)
        self.lyt_vert_filter_keyword = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_keyword.setObjectName("lyt_vert_filter_keyword")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ico_keyword = QtWidgets.QLabel(self.layoutWidget_2)
        self.ico_keyword.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ico_keyword.setFont(font)
        self.ico_keyword.setText("")
        self.ico_keyword.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/users.svg"))
        self.ico_keyword.setScaledContents(True)
        self.ico_keyword.setObjectName("ico_keyword")
        self.horizontalLayout_5.addWidget(self.ico_keyword)
        self.lbl_keyword = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_keyword.setFont(font)
        self.lbl_keyword.setObjectName("lbl_keyword")
        self.horizontalLayout_5.addWidget(self.lbl_keyword)
        spacerItem3 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lyt_vert_filter_keyword.addLayout(self.horizontalLayout_5)
        self.cbb_keyword = QtWidgets.QComboBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_keyword.sizePolicy().hasHeightForWidth())
        self.cbb_keyword.setSizePolicy(sizePolicy)
        self.cbb_keyword.setMinimumSize(QtCore.QSize(30, 0))
        self.cbb_keyword.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbb_keyword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_keyword.setObjectName("cbb_keyword")
        self.lyt_vert_filter_keyword.addWidget(self.cbb_keyword)
        self.lyt_vert_filters_right.addLayout(self.lyt_vert_filter_keyword)
        self.lyt_advc_search.addLayout(self.lyt_vert_filters_right)
        self.lbl_result = QtWidgets.QLabel(self.Filters)
        self.lbl_result.setGeometry(QtCore.QRect(240, 190, 261, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_result.setFont(font)
        self.lbl_result.setStyleSheet("")
        self.lbl_result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_result.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_result.setObjectName("lbl_result")
        self.btn_reinit = QtWidgets.QPushButton(self.Filters)
        self.btn_reinit.setGeometry(QtCore.QRect(520, 200, 41, 31))
        self.btn_reinit.setMinimumSize(QtCore.QSize(33, 30))
        self.btn_reinit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_reinit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reinit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reinit.setIcon(icon1)
        self.btn_reinit.setIconSize(QtCore.QSize(18, 18))
        self.btn_reinit.setObjectName("btn_reinit")
        self.btn_launch_export = QtWidgets.QPushButton(self.Export)
        self.btn_launch_export.setGeometry(QtCore.QRect(140, 670, 554, 40))
        self.btn_launch_export.setMinimumSize(QtCore.QSize(201, 0))
        self.btn_launch_export.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_launch_export.setFont(font)
        self.btn_launch_export.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/export/send-o.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_launch_export.setIcon(icon2)
        self.btn_launch_export.setObjectName("btn_launch_export")
        self.lbl_admin_shares = QtWidgets.QLabel(self.Export)
        self.lbl_admin_shares.setGeometry(QtCore.QRect(180, 50, 361, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_admin_shares.setFont(font)
        self.lbl_admin_shares.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_admin_shares.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_admin_shares.setObjectName("lbl_admin_shares")
        self.ico_admin_shares = QtWidgets.QLabel(self.Export)
        self.ico_admin_shares.setGeometry(QtCore.QRect(110, 50, 61, 61))
        self.ico_admin_shares.setText("")
        self.ico_admin_shares.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/export/favicon_isogeo.gif"))
        self.ico_admin_shares.setIndent(-2)
        self.ico_admin_shares.setObjectName("ico_admin_shares")
        self.btn_admin_shares = QtWidgets.QPushButton(self.Export)
        self.btn_admin_shares.setGeometry(QtCore.QRect(550, 60, 151, 40))
        self.btn_admin_shares.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_admin_shares.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_admin_shares.setFont(font)
        self.btn_admin_shares.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/export/shares.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_admin_shares.setIcon(icon3)
        self.btn_admin_shares.setObjectName("btn_admin_shares")
        self.pgb_exports = QtWidgets.QProgressBar(self.Export)
        self.pgb_exports.setGeometry(QtCore.QRect(30, 740, 741, 31))
        self.pgb_exports.setProperty("value", 24)
        self.pgb_exports.setObjectName("pgb_exports")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Export)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 450, 751, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.lyt_exports_formats_selection = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.lyt_exports_formats_selection.setContentsMargins(0, 0, 0, 0)
        self.lyt_exports_formats_selection.setObjectName("lyt_exports_formats_selection")
        self.Excel = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.Excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Excel.setCheckable(True)
        self.Excel.setObjectName("Excel")
        self.ico_excel = QtWidgets.QLabel(self.Excel)
        self.ico_excel.setGeometry(QtCore.QRect(50, 30, 141, 151))
        self.ico_excel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ico_excel.setText("")
        self.ico_excel.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/excel.svg"))
        self.ico_excel.setIndent(-2)
        self.ico_excel.setObjectName("ico_excel")
        self.lyt_exports_formats_selection.addWidget(self.Excel)
        self.Word = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.Word.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Word.setCheckable(True)
        self.Word.setObjectName("Word")
        self.ico_word = QtWidgets.QLabel(self.Word)
        self.ico_word.setGeometry(QtCore.QRect(60, 30, 161, 141))
        self.ico_word.setText("")
        self.ico_word.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/word.svg"))
        self.ico_word.setIndent(-2)
        self.ico_word.setObjectName("ico_word")
        self.lyt_exports_formats_selection.addWidget(self.Word)
        self.XML = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.XML.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.XML.setCheckable(True)
        self.XML.setObjectName("XML")
        self.ico_xml = QtWidgets.QLabel(self.XML)
        self.ico_xml.setGeometry(QtCore.QRect(50, 30, 141, 141))
        self.ico_xml.setText("")
        self.ico_xml.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/xml.svg"))
        self.ico_xml.setScaledContents(True)
        self.ico_xml.setIndent(-2)
        self.ico_xml.setObjectName("ico_xml")
        self.lyt_exports_formats_selection.addWidget(self.XML)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.addTab(self.Export, icon4, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setAutoFillBackground(True)
        self.Settings.setObjectName("Settings")
        self.groupBox_ressources = QtWidgets.QGroupBox(self.Settings)
        self.groupBox_ressources.setGeometry(QtCore.QRect(20, 560, 751, 149))
        self.groupBox_ressources.setObjectName("groupBox_ressources")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_ressources)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lbl_report = QtWidgets.QLabel(self.groupBox_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_report.setFont(font)
        self.lbl_report.setObjectName("lbl_report")
        self.horizontalLayout_24.addWidget(self.lbl_report)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.btn_log_dir = QtWidgets.QPushButton(self.groupBox_ressources)
        self.btn_log_dir.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_log_dir.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_log_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_log_dir.setAutoFillBackground(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/settings/folder-open-o.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_log_dir.setIcon(icon5)
        self.btn_log_dir.setObjectName("btn_log_dir")
        self.horizontalLayout_24.addWidget(self.btn_log_dir)
        self.btn_report = QtWidgets.QPushButton(self.groupBox_ressources)
        self.btn_report.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_report.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_report.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_report.setAutoFillBackground(True)
        self.btn_report.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/settings/bullhorn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_report.setIcon(icon6)
        self.btn_report.setObjectName("btn_report")
        self.horizontalLayout_24.addWidget(self.btn_report)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lbl_help = QtWidgets.QLabel(self.groupBox_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_help.setFont(font)
        self.lbl_help.setObjectName("lbl_help")
        self.horizontalLayout_23.addWidget(self.lbl_help)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem5)
        self.btn_help = QtWidgets.QPushButton(self.groupBox_ressources)
        self.btn_help.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_help.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_help.setAutoFillBackground(True)
        self.btn_help.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/settings/question.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_help.setIcon(icon7)
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout_23.addWidget(self.btn_help)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lbl_credits = QtWidgets.QLabel(self.groupBox_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_credits.setFont(font)
        self.lbl_credits.setObjectName("lbl_credits")
        self.horizontalLayout_22.addWidget(self.lbl_credits)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.btn_credits = QtWidgets.QPushButton(self.groupBox_ressources)
        self.btn_credits.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_credits.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_credits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_credits.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/settings/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_credits.setIcon(icon8)
        self.btn_credits.setObjectName("btn_credits")
        self.horizontalLayout_22.addWidget(self.btn_credits)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.groupBox_auth = QtWidgets.QGroupBox(self.Settings)
        self.groupBox_auth.setGeometry(QtCore.QRect(20, 310, 751, 241))
        self.groupBox_auth.setObjectName("groupBox_auth")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_auth)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txt_shares = QtWidgets.QTextBrowser(self.groupBox_auth)
        self.txt_shares.setObjectName("txt_shares")
        self.gridLayout_5.addWidget(self.txt_shares, 1, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbl_auth = QtWidgets.QLabel(self.groupBox_auth)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_auth.setFont(font)
        self.lbl_auth.setObjectName("lbl_auth")
        self.horizontalLayout_21.addWidget(self.lbl_auth)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem7)
        self.btn_change_user = QtWidgets.QPushButton(self.groupBox_auth)
        self.btn_change_user.setMinimumSize(QtCore.QSize(91, 24))
        self.btn_change_user.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/settings/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_change_user.setIcon(icon9)
        self.btn_change_user.setObjectName("btn_change_user")
        self.horizontalLayout_21.addWidget(self.btn_change_user)
        self.gridLayout_5.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.Settings)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 751, 271))
        self.groupBox.setObjectName("groupBox")
        self.lbl_output_directory_name = QtWidgets.QLabel(self.groupBox)
        self.lbl_output_directory_name.setGeometry(QtCore.QRect(20, 40, 111, 31))
        self.lbl_output_directory_name.setObjectName("lbl_output_directory_name")
        self.txt_uid = QtWidgets.QLineEdit(self.groupBox)
        self.txt_uid.setGeometry(QtCore.QRect(670, 200, 61, 30))
        self.txt_uid.setMinimumSize(QtCore.QSize(20, 30))
        self.txt_uid.setAutoFillBackground(True)
        self.txt_uid.setInputMask("")
        self.txt_uid.setText("")
        self.txt_uid.setObjectName("txt_uid")
        self.lbl_timestamp = QtWidgets.QLabel(self.groupBox)
        self.lbl_timestamp.setGeometry(QtCore.QRect(20, 200, 131, 31))
        self.lbl_timestamp.setObjectName("lbl_timestamp")
        self.lbl_uid = QtWidgets.QLabel(self.groupBox)
        self.lbl_uid.setGeometry(QtCore.QRect(540, 200, 111, 31))
        self.lbl_uid.setObjectName("lbl_uid")
        self.cbb_timestamp = QtWidgets.QComboBox(self.groupBox)
        self.cbb_timestamp.setGeometry(QtCore.QRect(180, 200, 261, 31))
        self.cbb_timestamp.setObjectName("cbb_timestamp")
        self.checkBox_zip_xml = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_zip_xml.setGeometry(QtCore.QRect(530, 150, 16, 21))
        self.checkBox_zip_xml.setText("")
        self.checkBox_zip_xml.setObjectName("checkBox_zip_xml")
        self.lbl_zip = QtWidgets.QLabel(self.groupBox)
        self.lbl_zip.setGeometry(QtCore.QRect(560, 150, 151, 31))
        self.lbl_zip.setObjectName("lbl_zip")
        self.checkBox_display_att_occ = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_display_att_occ.setGeometry(QtCore.QRect(280, 150, 16, 21))
        self.checkBox_display_att_occ.setObjectName("checkBox_display_att_occ")
        self.lbl_display_att_occ = QtWidgets.QLabel(self.groupBox)
        self.lbl_display_att_occ.setGeometry(QtCore.QRect(310, 150, 171, 31))
        self.lbl_display_att_occ.setObjectName("lbl_display_att_occ")
        self.lbl_display_cat_ind = QtWidgets.QLabel(self.groupBox)
        self.lbl_display_cat_ind.setGeometry(QtCore.QRect(80, 150, 151, 31))
        self.lbl_display_cat_ind.setObjectName("lbl_display_cat_ind")
        self.checkBox_display_cat_ind = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_display_cat_ind.setGeometry(QtCore.QRect(50, 150, 16, 21))
        self.checkBox_display_cat_ind.setText("")
        self.checkBox_display_cat_ind.setObjectName("checkBox_display_cat_ind")
        self.txt_output_fileprefix = QtWidgets.QLineEdit(self.groupBox)
        self.txt_output_fileprefix.setGeometry(QtCore.QRect(170, 90, 521, 30))
        self.txt_output_fileprefix.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_output_fileprefix.setAutoFillBackground(True)
        self.txt_output_fileprefix.setInputMask("")
        self.txt_output_fileprefix.setText("")
        self.txt_output_fileprefix.setObjectName("txt_output_fileprefix")
        self.lbl_output_fileprefix = QtWidgets.QLabel(self.groupBox)
        self.lbl_output_fileprefix.setGeometry(QtCore.QRect(20, 90, 111, 31))
        self.lbl_output_fileprefix.setObjectName("lbl_output_fileprefix")
        self.lbl_directory_name = QtWidgets.QLabel(self.groupBox)
        self.lbl_directory_name.setGeometry(QtCore.QRect(170, 40, 521, 29))
        self.lbl_directory_name.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbl_directory_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_directory_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_directory_name.setObjectName("lbl_directory_name")
        self.btn_directory_change = QtWidgets.QToolButton(self.groupBox)
        self.btn_directory_change.setGeometry(QtCore.QRect(700, 40, 31, 31))
        self.btn_directory_change.setObjectName("btn_directory_change")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/gear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.addTab(self.Settings, icon10, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        self.Filters.setTitle(_translate("TabWidget", "Filters"))
        self.lbl_share.setText(_translate("TabWidget", "Share"))
        self.lbl_owner.setText(_translate("TabWidget", "Metadata Owner"))
        self.lbl_type.setText(_translate("TabWidget", "Resource type"))
        self.lbl_keyword.setText(_translate("TabWidget", "Keyword"))
        self.lbl_result.setText(_translate("TabWidget", "<html><head/><body><p align=\"center\">150 metadata are ready to be exported</p></body></html>"))
        self.btn_reinit.setToolTip(_translate("TabWidget", "Reset all input fields"))
        self.btn_launch_export.setToolTip(_translate("TabWidget", "Launch export"))
        self.btn_launch_export.setText(_translate("TabWidget", "Launch export"))
        self.lbl_admin_shares.setText(_translate("TabWidget", "<html><head/><body><p align=\"center\"><span style=\" font-weight:400;\">150 </span>metadata<span style=\" font-weight:400;\"> in 2 </span>shares<span style=\" font-weight:400;\"> owned by 3 </span>workgroups</p></body></html>"))
        self.btn_admin_shares.setToolTip(_translate("TabWidget", "Admin shares"))
        self.btn_admin_shares.setText(_translate("TabWidget", " Admin shares"))
        self.Excel.setTitle(_translate("TabWidget", "Excel"))
        self.Word.setTitle(_translate("TabWidget", "Word"))
        self.XML.setTitle(_translate("TabWidget", "XML ISO 19139"))
        TabWidget.setTabText(TabWidget.indexOf(self.Export), _translate("TabWidget", "Export"))
        self.groupBox_ressources.setTitle(_translate("TabWidget", "Resources"))
        self.lbl_report.setText(_translate("TabWidget", "Report an issue on the bug tracker"))
        self.btn_log_dir.setToolTip(_translate("TabWidget", "Get the log file: \"log_isogeo_isogeo2office.log\""))
        self.btn_log_dir.setText(_translate("TabWidget", "LOG File"))
        self.lbl_help.setText(_translate("TabWidget", "Open online application help"))
        self.btn_help.setToolTip(_translate("TabWidget", "Open online help in default browser"))
        self.lbl_credits.setText(_translate("TabWidget", "Open application credits"))
        self.btn_credits.setToolTip(_translate("TabWidget", "Open credits popup"))
        self.groupBox_auth.setTitle(_translate("TabWidget", "Authentication settings"))
        self.lbl_auth.setText(_translate("TabWidget", "Set application authentication:"))
        self.groupBox.setTitle(_translate("TabWidget", "Export settings"))
        self.lbl_output_directory_name.setText(_translate("TabWidget", "Output repository :"))
        self.txt_uid.setToolTip(_translate("TabWidget", "Enter output file name"))
        self.txt_uid.setPlaceholderText(_translate("TabWidget", "5"))
        self.lbl_timestamp.setText(_translate("TabWidget", "Display Timestamp :"))
        self.lbl_uid.setText(_translate("TabWidget", "UID chars [0 - 8]: "))
        self.checkBox_zip_xml.setToolTip(_translate("TabWidget", "Export metadata in XML ISO 19139"))
        self.lbl_zip.setText(_translate("TabWidget", "Pack all XML into one .zip"))
        self.checkBox_display_att_occ.setToolTip(_translate("TabWidget", "Export metadata in XML ISO 19139"))
        self.checkBox_display_att_occ.setText(_translate("TabWidget", "Display attributes ocurrences :"))
        self.lbl_display_att_occ.setText(_translate("TabWidget", "Display attributs occurrence"))
        self.lbl_display_cat_ind.setText(_translate("TabWidget", "Display catalog indicators"))
        self.checkBox_display_cat_ind.setToolTip(_translate("TabWidget", "Export metadata in XML ISO 19139"))
        self.txt_output_fileprefix.setToolTip(_translate("TabWidget", "Enter output file name"))
        self.txt_output_fileprefix.setPlaceholderText(_translate("TabWidget", "isogeo2office"))
        self.lbl_output_fileprefix.setText(_translate("TabWidget", "Output fileprefix :"))
        self.lbl_directory_name.setText(_translate("TabWidget", "Output"))
        self.btn_directory_change.setText(_translate("TabWidget", "..."))
        TabWidget.setTabText(TabWidget.indexOf(self.Settings), _translate("TabWidget", "Settings"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

