language: python
required: sudo
python:
  - "3.5"
  - "3.6"

cache: pip

# dependencies
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - sudo apt-get install python-tk
  - "pip install --upgrade -r requirements.txt"
  - "pip install --upgrade -r tests/requirements_test.txt"

# run tests
script:
  # get fixtures
  - python tests/fixturing.py
  # unit tests
  - coverage run -m unittest discover -s tests/
  # main
  - pycodestyle isogeo2office.py --ignore="E265,E501" --statistics --show-source
  # export modules
  - pycodestyle modules/export/isogeo2docx.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle modules/export/isogeo2xlsx.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle modules/export/isogeo_stats.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle modules/export/formatter.py --ignore="E265,E501" --statistics --show-source
  # UI
  - pycodestyle modules/ui/tooltip.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle modules/ui/frame_excel.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle modules/ui/frame_general.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle modules/ui/frame_word.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle modules/ui/frame_xml.py --ignore="E265,E501" --statistics --show-source
  - pycodestyle modules/ui/ui_app_settings.py --ignore="E265,E501" --statistics --show-source
  # utils
  - pycodestyle modules/utils/utils.py --ignore="E265,E501" --statistics --show-source

# coverage reporting
after_success:
- codecov

