version: 2.0.{build}

clone_depth: 50

environment:
  matrix:
    - PYTHON: C:\\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
      TEST_LIBRARIES_ONLY: False

    - PYTHON: C:\\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32
      TEST_LIBRARIES_ONLY: False


init:
  # Uncomment the line below to enable Remote Desktop access to the build worker
  # VM. See https://www.appveyor.com/docs/how-to/rdp-to-build-worker/.
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - ECHO \"%APPVEYOR_SCHEDULED_BUILD%\"
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  # Free up some disk space; exceeding the limit of 90 GB results in a
  # locked-out account. The Qt directory takes over 30 GB. Do this in the
  # background.
  - ps: Start-Process -FilePath "$env:comspec" -ArgumentList "/c rmdir C:\Qt /s /q"

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'


install:
  # Upgrade pip & co
  - "%PYTHON%\\python.exe -m pip install -U pip pipenv setuptools wheel"

build:
  - ps: .\build.ps1

test: off

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*
