# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Install'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36_VS17_64bits:
        python.version: '3.6'
        python.arch: 'x64'
      Python36_VS17_32bits:
        python.version: '3.6'
        python.arch: 'x86'
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.arch)'

  - script: python -m pip install -U pip && pip install -U -r requirements.txt && pip install -U -r requirements_dev.txt
    displayName: 'Install dependencies'

  - script: |
      pylupdate5 -noobsolete -verbose isogeo2office.pro
      pyrcc5 resources.qrc -o resources_rc.py
      pyuic5 -x modules\\ui\\auth\\ui_authentication.ui -o modules\\ui\\auth\\ui_authentication.py"
      pyuic5 -x modules\\ui\\credits\\ui_credits.ui -o modules\\ui\\credits\\ui_credits.py
      pyuic5 -x modules\\ui\\main\\ui_win_IsogeoToOffice.ui -o modules\\ui\\main\\ui_win_IsogeoToOffice.py
    displayName: 'PyQt processing'

  - script: pyinstaller.exe -y bundle_isogeo2office.spec
    displayName: 'Building the executable'

  # Archive Files
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'dist/'
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      archiveFile: '$(Build.ArtifactStagingDirectory)/IsogeoToOffice-$(Build.SourceBranchName)-b$(Build.BuildId).zip' 
      replaceExistingArchive: true 

  - task: CopyFiles@2
    displayName: 'Copy File to: $(TargetFolder)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: 'IsogeoToOffice-$(Build.SourceBranchName)-b$(Build.BuildId).zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: IsogeoToOffice'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
      ArtifactName: IsogeoToOffice
