# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\modules\ui\credits\ui_credits.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlg_credits(object):
    def setupUi(self, dlg_credits):
        dlg_credits.setObjectName("dlg_credits")
        dlg_credits.resize(540, 650)
        dlg_credits.setMinimumSize(QtCore.QSize(540, 650))
        dlg_credits.setMaximumSize(QtCore.QSize(540, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/gavel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_credits.setWindowIcon(icon)
        dlg_credits.setWindowOpacity(0.95)
        dlg_credits.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        dlg_credits.setSizeGripEnabled(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(dlg_credits)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grp_realization = QtWidgets.QGroupBox(dlg_credits)
        self.grp_realization.setMaximumSize(QtCore.QSize(500, 175))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.grp_realization.setFont(font)
        self.grp_realization.setFlat(True)
        self.grp_realization.setObjectName("grp_realization")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.grp_realization)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_isogeo_logo = QtWidgets.QLabel(self.grp_realization)
        self.lbl_isogeo_logo.setMinimumSize(QtCore.QSize(222, 102))
        self.lbl_isogeo_logo.setMaximumSize(QtCore.QSize(222, 102))
        self.lbl_isogeo_logo.setText("")
        self.lbl_isogeo_logo.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/credits/isogeo.png"))
        self.lbl_isogeo_logo.setScaledContents(False)
        self.lbl_isogeo_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_isogeo_logo.setOpenExternalLinks(True)
        self.lbl_isogeo_logo.setObjectName("lbl_isogeo_logo")
        self.horizontalLayout_4.addWidget(self.lbl_isogeo_logo)
        self.lbl_isogeo_punchline = QtWidgets.QLabel(self.grp_realization)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.lbl_isogeo_punchline.setFont(font)
        self.lbl_isogeo_punchline.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_isogeo_punchline.setOpenExternalLinks(True)
        self.lbl_isogeo_punchline.setObjectName("lbl_isogeo_punchline")
        self.horizontalLayout_4.addWidget(self.lbl_isogeo_punchline)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.grp_realization)
        self.grp_sponsors = QtWidgets.QGroupBox(dlg_credits)
        self.grp_sponsors.setMaximumSize(QtCore.QSize(500, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.grp_sponsors.setFont(font)
        self.grp_sponsors.setFlat(True)
        self.grp_sponsors.setObjectName("grp_sponsors")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.grp_sponsors)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbl_smavd_url = QtWidgets.QLabel(self.grp_sponsors)
        self.lbl_smavd_url.setMaximumSize(QtCore.QSize(217, 40))
        self.lbl_smavd_url.setText("<html><head/><body><p align=\"center\"><a href=\"http://www.smavd.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">Syndicat Mixte d\'Aménagement<br/>de la Durance (SMAVD)</span></a></p></body></html>")
        self.lbl_smavd_url.setWordWrap(True)
        self.lbl_smavd_url.setOpenExternalLinks(False)
        self.lbl_smavd_url.setObjectName("lbl_smavd_url")
        self.gridLayout_5.addWidget(self.lbl_smavd_url, 0, 0, 1, 1)
        self.lbl_smavd_logo = QtWidgets.QLabel(self.grp_sponsors)
        self.lbl_smavd_logo.setMaximumSize(QtCore.QSize(217, 40))
        self.lbl_smavd_logo.setText("")
        self.lbl_smavd_logo.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/credits/sponsor_logo_SMAVD.jpg"))
        self.lbl_smavd_logo.setScaledContents(False)
        self.lbl_smavd_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_smavd_logo.setOpenExternalLinks(True)
        self.lbl_smavd_logo.setObjectName("lbl_smavd_logo")
        self.gridLayout_5.addWidget(self.lbl_smavd_logo, 0, 3, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_5)
        self.line_1 = QtWidgets.QFrame(self.grp_sponsors)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout_9.addWidget(self.line_1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lbl_lorient_url = QtWidgets.QLabel(self.grp_sponsors)
        self.lbl_lorient_url.setMaximumSize(QtCore.QSize(217, 40))
        self.lbl_lorient_url.setText("<html><head/><body><p align=\"center\"><a href=\"https://www.ampmetropole.fr\"><span style=\" text-decoration: underline; color:#0000ff;\">Métropole Aix Marseille Provence</span></a></p></body></html>")
        self.lbl_lorient_url.setObjectName("lbl_lorient_url")
        self.gridLayout_6.addWidget(self.lbl_lorient_url, 1, 0, 1, 1)
        self.lbl_lorient_logo = QtWidgets.QLabel(self.grp_sponsors)
        self.lbl_lorient_logo.setMaximumSize(QtCore.QSize(217, 40))
        self.lbl_lorient_logo.setText("")
        self.lbl_lorient_logo.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/credits/sponsor_logo_metropole_aix_marseille_provence.png"))
        self.lbl_lorient_logo.setScaledContents(False)
        self.lbl_lorient_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lorient_logo.setWordWrap(False)
        self.lbl_lorient_logo.setOpenExternalLinks(True)
        self.lbl_lorient_logo.setObjectName("lbl_lorient_logo")
        self.gridLayout_6.addWidget(self.lbl_lorient_logo, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_6)
        self.line_2 = QtWidgets.QFrame(self.grp_sponsors)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbl_aev_url = QtWidgets.QLabel(self.grp_sponsors)
        self.lbl_aev_url.setMaximumSize(QtCore.QSize(217, 40))
        self.lbl_aev_url.setObjectName("lbl_aev_url")
        self.gridLayout_7.addWidget(self.lbl_aev_url, 0, 0, 1, 1)
        self.lbl_aev_logo = QtWidgets.QLabel(self.grp_sponsors)
        self.lbl_aev_logo.setMaximumSize(QtCore.QSize(217, 40))
        self.lbl_aev_logo.setText("")
        self.lbl_aev_logo.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/credits/sponsor_logo_aev.png"))
        self.lbl_aev_logo.setObjectName("lbl_aev_logo")
        self.gridLayout_7.addWidget(self.lbl_aev_logo, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_9.addLayout(self.gridLayout_7)
        self.verticalLayout.addWidget(self.grp_sponsors)
        self.grp_sources = QtWidgets.QGroupBox(dlg_credits)
        self.grp_sources.setEnabled(True)
        self.grp_sources.setMaximumSize(QtCore.QSize(500, 150))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.grp_sources.setFont(font)
        self.grp_sources.setFlat(True)
        self.grp_sources.setCheckable(False)
        self.grp_sources.setObjectName("grp_sources")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.grp_sources)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ico_lgplv3 = QtWidgets.QLabel(self.grp_sources)
        self.ico_lgplv3.setMinimumSize(QtCore.QSize(32, 32))
        self.ico_lgplv3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ico_lgplv3.setToolTip("")
        self.ico_lgplv3.setAutoFillBackground(True)
        self.ico_lgplv3.setText("")
        self.ico_lgplv3.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/credits/lgplv3.png"))
        self.ico_lgplv3.setScaledContents(True)
        self.ico_lgplv3.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_lgplv3.setObjectName("ico_lgplv3")
        self.gridLayout_4.addWidget(self.ico_lgplv3, 0, 2, 1, 1)
        self.lbl_source_repository = QtWidgets.QLabel(self.grp_sources)
        self.lbl_source_repository.setScaledContents(True)
        self.lbl_source_repository.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_source_repository.setObjectName("lbl_source_repository")
        self.gridLayout_4.addWidget(self.lbl_source_repository, 1, 1, 1, 1)
        self.lbl_license_logo_gpl3 = QtWidgets.QLabel(self.grp_sources)
        self.lbl_license_logo_gpl3.setText("<html><head/><body><p><a href=\"https://fr.wikipedia.org/wiki/Licence_publique_g%C3%A9n%C3%A9rale_GNU\"><span style=\" text-decoration: underline; color:#0000ff;\">LGPL v3 - Wikipédia</span></a></p></body></html>")
        self.lbl_license_logo_gpl3.setScaledContents(True)
        self.lbl_license_logo_gpl3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_license_logo_gpl3.setOpenExternalLinks(True)
        self.lbl_license_logo_gpl3.setObjectName("lbl_license_logo_gpl3")
        self.gridLayout_4.addWidget(self.lbl_license_logo_gpl3, 1, 2, 1, 1)
        self.ico_github = QtWidgets.QLabel(self.grp_sources)
        self.ico_github.setMaximumSize(QtCore.QSize(100, 100))
        self.ico_github.setToolTip("")
        self.ico_github.setAutoFillBackground(True)
        self.ico_github.setText("")
        self.ico_github.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/credits/github.svg"))
        self.ico_github.setScaledContents(True)
        self.ico_github.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_github.setObjectName("ico_github")
        self.gridLayout_4.addWidget(self.ico_github, 0, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.grp_sources)
        self.btn_ok_close = QtWidgets.QDialogButtonBox(dlg_credits)
        self.btn_ok_close.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btn_ok_close.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ok_close.setAutoFillBackground(False)
        self.btn_ok_close.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btn_ok_close.setOrientation(QtCore.Qt.Horizontal)
        self.btn_ok_close.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.btn_ok_close.setCenterButtons(True)
        self.btn_ok_close.setObjectName("btn_ok_close")
        self.verticalLayout.addWidget(self.btn_ok_close)
        self.verticalLayout.setStretch(0, 200)
        self.verticalLayout.setStretch(2, 100)
        self.verticalLayout.setStretch(3, 100)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(dlg_credits)
        self.btn_ok_close.accepted.connect(dlg_credits.accept)
        self.btn_ok_close.rejected.connect(dlg_credits.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_credits)

    def retranslateUi(self, dlg_credits):
        _translate = QtCore.QCoreApplication.translate
        dlg_credits.setWindowTitle(_translate("dlg_credits", "Credits"))
        self.grp_realization.setTitle(_translate("dlg_credits", "Realization"))
        self.lbl_isogeo_punchline.setText(_translate("dlg_credits", "<html><head/><body><p><a href=\"https://www.isogeo.com\"><span style=\" color:#6480a7;\">Easy access </span></a></p><p><a href=\"https://www.isogeo.com\"><span style=\" color:#6480a7;\">to geodata!</span></a></p></body></html>"))
        self.grp_sponsors.setTitle(_translate("dlg_credits", "Sponsors"))
        self.lbl_aev_url.setText(_translate("dlg_credits", "<html><head/><body><p align=\"center\"><a href=\"http://www.aev-iledefrance.fr/\"><span style=\" text-decoration: underline; color:#0000ff;\">Agence des Espaces Verts<br/>d\'Ile de France (AEV)</span></a></p></body></html>"))
        self.grp_sources.setTitle(_translate("dlg_credits", "Sources and license"))
        self.lbl_source_repository.setText(_translate("dlg_credits", "<html><head/><body><p><a href=\"https://github.com/isogeo/isogeo-2-office\"><span style=\" text-decoration: underline; color:#0000ff;\">Code hosted on Github</span></a></p></body></html>"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg_credits = QtWidgets.QDialog()
    ui = Ui_dlg_credits()
    ui.setupUi(dlg_credits)
    dlg_credits.show()
    sys.exit(app.exec_())

