# -*- coding: UTF-8 -*-
#! python3

"""
    Matching table between Isogeo metadata model and Excle columns for Isogeo to Office.
"""

RASTER_COLUMNS = {
    "_created": "AK",
    "_creator": "E",
    "_id": "AJ",
    "_modified": "AL",
    "abstract": "C",
    "collectionContext": "I",
    "collectionMethod": "J",
    "conditions": "Z",
    "contacts": "AF",
    "coordinateSystem": "",
    "created": "O",
    "distance": "",
    "editionProfile": "",
    "encoding": "",
    "envelope": "",
    "events": "",
    "featureAttributes": "",
    "features": "Y",
    "format": "",
    "formatVersion": "",
    "geometry": "",
    "keywords": "F",
    "language": "AM",
    "layers": "",
    "limitations": "AA",
    "links": "",
    "modified": "Q",
    "name": "B",
    "operations": "",
    "path": "D",
    "precision": "",
    "published": "",
    "scale": "X",
    "series": "",
    "serviceLayers": "",
    "specifications": "X",
    "tags": "",
    "title": "A",
    "topologicalConsistency": "AC",
    "type": "",
    "updateFrequency": "",
    "validFrom": "",
    "validTo": "",
    "validityComment": "",
}
