# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\modules\ui\auth\ui_authentication.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlg_authentication(object):
    def setupUi(self, dlg_authentication):
        dlg_authentication.setObjectName("dlg_authentication")
        dlg_authentication.resize(640, 392)
        dlg_authentication.setMinimumSize(QtCore.QSize(640, 380))
        dlg_authentication.setMaximumSize(QtCore.QSize(640, 540))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_authentication.setWindowIcon(icon)
        dlg_authentication.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        dlg_authentication.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_authentication)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grb_connection_ready = QtWidgets.QGroupBox(dlg_authentication)
        self.grb_connection_ready.setMinimumSize(QtCore.QSize(500, 150))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.grb_connection_ready.setFont(font)
        self.grb_connection_ready.setAutoFillBackground(True)
        self.grb_connection_ready.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.grb_connection_ready.setFlat(True)
        self.grb_connection_ready.setObjectName("grb_connection_ready")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grb_connection_ready)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_app_secret = QtWidgets.QLabel(self.grb_connection_ready)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_app_secret.sizePolicy().hasHeightForWidth())
        self.lbl_app_secret.setSizePolicy(sizePolicy)
        self.lbl_app_secret.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_app_secret.setFont(font)
        self.lbl_app_secret.setAutoFillBackground(True)
        self.lbl_app_secret.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_app_secret.setScaledContents(True)
        self.lbl_app_secret.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_app_secret.setObjectName("lbl_app_secret")
        self.gridLayout_2.addWidget(self.lbl_app_secret, 3, 0, 1, 1)
        self.lbl_app_id = QtWidgets.QLabel(self.grb_connection_ready)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_app_id.sizePolicy().hasHeightForWidth())
        self.lbl_app_id.setSizePolicy(sizePolicy)
        self.lbl_app_id.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_app_id.setFont(font)
        self.lbl_app_id.setAutoFillBackground(True)
        self.lbl_app_id.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_app_id.setScaledContents(True)
        self.lbl_app_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_app_id.setObjectName("lbl_app_id")
        self.gridLayout_2.addWidget(self.lbl_app_id, 2, 0, 1, 1)
        self.ent_app_id = QtWidgets.QLineEdit(self.grb_connection_ready)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_app_id.sizePolicy().hasHeightForWidth())
        self.ent_app_id.setSizePolicy(sizePolicy)
        self.ent_app_id.setMinimumSize(QtCore.QSize(475, 25))
        self.ent_app_id.setMaximumSize(QtCore.QSize(800, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ent_app_id.setFont(font)
        self.ent_app_id.setToolTip("")
        self.ent_app_id.setAutoFillBackground(True)
        self.ent_app_id.setText("")
        self.ent_app_id.setMaxLength(100)
        self.ent_app_id.setFrame(True)
        self.ent_app_id.setReadOnly(True)
        self.ent_app_id.setPlaceholderText("isogeo-to-office-a1b23c4d5f6g7h8i9j10kl11mn13op14")
        self.ent_app_id.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.ent_app_id.setObjectName("ent_app_id")
        self.gridLayout_2.addWidget(self.ent_app_id, 2, 1, 1, 1)
        self.lbl_api_url = QtWidgets.QLabel(self.grb_connection_ready)
        self.lbl_api_url.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_api_url.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_api_url.setFont(font)
        self.lbl_api_url.setAutoFillBackground(True)
        self.lbl_api_url.setScaledContents(True)
        self.lbl_api_url.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_api_url.setObjectName("lbl_api_url")
        self.gridLayout_2.addWidget(self.lbl_api_url, 4, 0, 1, 1)
        self.btn_browse_credentials = QtWidgets.QToolButton(self.grb_connection_ready)
        self.btn_browse_credentials.setMinimumSize(QtCore.QSize(475, 30))
        self.btn_browse_credentials.setMaximumSize(QtCore.QSize(800, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_browse_credentials.setFont(font)
        self.btn_browse_credentials.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse_credentials.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_browse_credentials.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/authentication/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_browse_credentials.setIcon(icon1)
        self.btn_browse_credentials.setIconSize(QtCore.QSize(16, 16))
        self.btn_browse_credentials.setCheckable(False)
        self.btn_browse_credentials.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_browse_credentials.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_browse_credentials.setAutoRaise(False)
        self.btn_browse_credentials.setArrowType(QtCore.Qt.NoArrow)
        self.btn_browse_credentials.setObjectName("btn_browse_credentials")
        self.gridLayout_2.addWidget(self.btn_browse_credentials, 0, 1, 1, 1)
        self.ent_app_secret = QtWidgets.QLineEdit(self.grb_connection_ready)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_app_secret.sizePolicy().hasHeightForWidth())
        self.ent_app_secret.setSizePolicy(sizePolicy)
        self.ent_app_secret.setMinimumSize(QtCore.QSize(475, 25))
        self.ent_app_secret.setMaximumSize(QtCore.QSize(800, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ent_app_secret.setFont(font)
        self.ent_app_secret.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ent_app_secret.setAutoFillBackground(True)
        self.ent_app_secret.setText("")
        self.ent_app_secret.setMaxLength(64)
        self.ent_app_secret.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.ent_app_secret.setReadOnly(True)
        self.ent_app_secret.setPlaceholderText("*******************************************")
        self.ent_app_secret.setObjectName("ent_app_secret")
        self.gridLayout_2.addWidget(self.ent_app_secret, 3, 1, 1, 1)
        self.lbl_api_url_value = QtWidgets.QLabel(self.grb_connection_ready)
        self.lbl_api_url_value.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_api_url_value.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.lbl_api_url_value.setFont(font)
        self.lbl_api_url_value.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lbl_api_url_value.setAutoFillBackground(True)
        self.lbl_api_url_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_api_url_value.setText("https://v1.api.isogeo.com/")
        self.lbl_api_url_value.setOpenExternalLinks(True)
        self.lbl_api_url_value.setObjectName("lbl_api_url_value")
        self.gridLayout_2.addWidget(self.lbl_api_url_value, 4, 1, 1, 1)
        self.chb_isogeo_editor = QtWidgets.QCheckBox(self.grb_connection_ready)
        self.chb_isogeo_editor.setMinimumSize(QtCore.QSize(300, 25))
        self.chb_isogeo_editor.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chb_isogeo_editor.setFont(font)
        self.chb_isogeo_editor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chb_isogeo_editor.setAutoFillBackground(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/authentication/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chb_isogeo_editor.setIcon(icon2)
        self.chb_isogeo_editor.setTristate(False)
        self.chb_isogeo_editor.setObjectName("chb_isogeo_editor")
        self.gridLayout_2.addWidget(self.chb_isogeo_editor, 5, 1, 1, 1)
        self.btn_ok_cancel = QtWidgets.QPushButton(self.grb_connection_ready)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok_cancel.sizePolicy().hasHeightForWidth())
        self.btn_ok_cancel.setSizePolicy(sizePolicy)
        self.btn_ok_cancel.setMinimumSize(QtCore.QSize(200, 25))
        self.btn_ok_cancel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_ok_cancel.setFont(font)
        self.btn_ok_cancel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btn_ok_cancel.setAutoFillBackground(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ok_cancel.setIcon(icon3)
        self.btn_ok_cancel.setDefault(False)
        self.btn_ok_cancel.setFlat(False)
        self.btn_ok_cancel.setObjectName("btn_ok_cancel")
        self.gridLayout_2.addWidget(self.btn_ok_cancel, 6, 1, 1, 1)
        self.ent_app_id.raise_()
        self.ent_app_secret.raise_()
        self.lbl_app_id.raise_()
        self.lbl_app_secret.raise_()
        self.chb_isogeo_editor.raise_()
        self.lbl_api_url_value.raise_()
        self.lbl_api_url.raise_()
        self.btn_browse_credentials.raise_()
        self.btn_ok_cancel.raise_()
        self.verticalLayout.addWidget(self.grb_connection_ready)
        self.grb_need_account = QtWidgets.QGroupBox(dlg_authentication)
        self.grb_need_account.setMinimumSize(QtCore.QSize(200, 150))
        self.grb_need_account.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.grb_need_account.setFont(font)
        self.grb_need_account.setAutoFillBackground(True)
        self.grb_need_account.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.grb_need_account.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grb_need_account.setFlat(True)
        self.grb_need_account.setObjectName("grb_need_account")
        self.gridLayout = QtWidgets.QGridLayout(self.grb_need_account)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_account_new = QtWidgets.QPushButton(self.grb_need_account)
        self.btn_account_new.setMinimumSize(QtCore.QSize(200, 30))
        self.btn_account_new.setMaximumSize(QtCore.QSize(700, 50))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_account_new.setFont(font)
        self.btn_account_new.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_account_new.setAutoFillBackground(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/authentication/send-o.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_account_new.setIcon(icon4)
        self.btn_account_new.setDefault(True)
        self.btn_account_new.setObjectName("btn_account_new")
        self.gridLayout.addWidget(self.btn_account_new, 1, 0, 1, 1)
        self.lbl_access_conditions = QtWidgets.QLabel(self.grb_need_account)
        self.lbl_access_conditions.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_access_conditions.setFont(font)
        self.lbl_access_conditions.setTextFormat(QtCore.Qt.RichText)
        self.lbl_access_conditions.setObjectName("lbl_access_conditions")
        self.gridLayout.addWidget(self.lbl_access_conditions, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.grb_need_account)

        self.retranslateUi(dlg_authentication)
        QtCore.QMetaObject.connectSlotsByName(dlg_authentication)
        dlg_authentication.setTabOrder(self.ent_app_id, self.chb_isogeo_editor)
        dlg_authentication.setTabOrder(self.chb_isogeo_editor, self.btn_account_new)

    def retranslateUi(self, dlg_authentication):
        _translate = QtCore.QCoreApplication.translate
        dlg_authentication.setWindowTitle(_translate("dlg_authentication", "Isogeo authentication settings"))
        self.grb_connection_ready.setTitle(_translate("dlg_authentication", "I already have Isogeo ID and SECRET for this application"))
        self.lbl_app_secret.setText(_translate("dlg_authentication", "Application SECRET:"))
        self.lbl_app_id.setText(_translate("dlg_authentication", "Application ID:"))
        self.lbl_api_url.setToolTip(_translate("dlg_authentication", "Only for information, the Isogeo API base URL"))
        self.lbl_api_url.setText(_translate("dlg_authentication", "API location:"))
        self.btn_browse_credentials.setToolTip(_translate("dlg_authentication", "Pick your credentials file"))
        self.btn_browse_credentials.setText(_translate("dlg_authentication", "Import the Isogeo API credentials file ..."))
        self.chb_isogeo_editor.setToolTip(_translate("dlg_authentication", "I\'ve got the power hey yeah heh!"))
        self.chb_isogeo_editor.setText(_translate("dlg_authentication", "I\'ve got edition rights on app.isogeo.com"))
        self.btn_ok_cancel.setToolTip(_translate("dlg_authentication", "Save credentials"))
        self.btn_ok_cancel.setText(_translate("dlg_authentication", "Apply"))
        self.grb_need_account.setTitle(_translate("dlg_authentication", "Don\'t have an account yet ?"))
        self.btn_account_new.setText(_translate("dlg_authentication", "Request plugin access"))
        self.lbl_access_conditions.setText(_translate("dlg_authentication", "<!DOCTYPE html>\n"
"<html>\n"
"<body>\n"
"\n"
"<ul>\n"
"    <li>Completely free to access generic Open Data</li>\n"
"    <li>Completely free to work with 20 of your geographic data and services (Isogeo account required)</li>\n"
"    <li>Ask for our annual plans to work with your whole geographic data and services !</li>\n"
"</ul> \n"
"\n"
"</body>\n"
"</html>\n"
""))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg_authentication = QtWidgets.QDialog()
    ui = Ui_dlg_authentication()
    ui.setupUi(dlg_authentication)
    dlg_authentication.show()
    sys.exit(app.exec_())

