# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\modules\ui\main\ui_IsogeoToOffice.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tabs_IsogeoToOffice(object):
    def setupUi(self, tabs_IsogeoToOffice):
        tabs_IsogeoToOffice.setObjectName("tabs_IsogeoToOffice")
        tabs_IsogeoToOffice.setEnabled(True)
        tabs_IsogeoToOffice.resize(626, 500)
        tabs_IsogeoToOffice.setMinimumSize(QtCore.QSize(500, 500))
        tabs_IsogeoToOffice.setMaximumSize(QtCore.QSize(800, 850))
        tabs_IsogeoToOffice.setFocusPolicy(QtCore.Qt.StrongFocus)
        tabs_IsogeoToOffice.setWindowTitle("Isogeo To Office")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs_IsogeoToOffice.setWindowIcon(icon)
        tabs_IsogeoToOffice.setAutoFillBackground(True)
        tabs_IsogeoToOffice.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        tabs_IsogeoToOffice.setTabPosition(QtWidgets.QTabWidget.North)
        tabs_IsogeoToOffice.setTabShape(QtWidgets.QTabWidget.Rounded)
        tabs_IsogeoToOffice.setTabBarAutoHide(False)
        self.Export = QtWidgets.QWidget()
        self.Export.setMinimumSize(QtCore.QSize(500, 0))
        self.Export.setObjectName("Export")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Export)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grp_filters = QtWidgets.QGroupBox(self.Export)
        self.grp_filters.setMinimumSize(QtCore.QSize(550, 150))
        self.grp_filters.setMaximumSize(QtCore.QSize(600, 200))
        self.grp_filters.setAutoFillBackground(False)
        self.grp_filters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.grp_filters.setObjectName("grp_filters")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grp_filters)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lyt_advc_search = QtWidgets.QHBoxLayout()
        self.lyt_advc_search.setObjectName("lyt_advc_search")
        self.lyt_vert_filters_left = QtWidgets.QVBoxLayout()
        self.lyt_vert_filters_left.setObjectName("lyt_vert_filters_left")
        self.lyt_vert_share = QtWidgets.QVBoxLayout()
        self.lyt_vert_share.setObjectName("lyt_vert_share")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ico_share = QtWidgets.QLabel(self.grp_filters)
        self.ico_share.setMaximumSize(QtCore.QSize(18, 18))
        self.ico_share.setText("")
        self.ico_share.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/share-alt.svg"))
        self.ico_share.setScaledContents(True)
        self.ico_share.setObjectName("ico_share")
        self.horizontalLayout.addWidget(self.ico_share)
        self.lbl_share = QtWidgets.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_share.setFont(font)
        self.lbl_share.setObjectName("lbl_share")
        self.horizontalLayout.addWidget(self.lbl_share)
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lyt_vert_share.addLayout(self.horizontalLayout)
        self.cbb_share = QtWidgets.QComboBox(self.grp_filters)
        self.cbb_share.setMinimumSize(QtCore.QSize(250, 25))
        self.cbb_share.setMaximumSize(QtCore.QSize(350, 35))
        self.cbb_share.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_share.setAutoFillBackground(True)
        self.cbb_share.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbb_share.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbb_share.setMinimumContentsLength(50)
        self.cbb_share.setObjectName("cbb_share")
        self.lyt_vert_share.addWidget(self.cbb_share)
        self.lyt_vert_filters_left.addLayout(self.lyt_vert_share)
        self.lyt_vert_filter_owner = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_owner.setObjectName("lyt_vert_filter_owner")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ico_owner = QtWidgets.QLabel(self.grp_filters)
        self.ico_owner.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ico_owner.setFont(font)
        self.ico_owner.setText("")
        self.ico_owner.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/users.svg"))
        self.ico_owner.setScaledContents(True)
        self.ico_owner.setObjectName("ico_owner")
        self.horizontalLayout_3.addWidget(self.ico_owner)
        self.lbl_owner = QtWidgets.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_owner.setFont(font)
        self.lbl_owner.setObjectName("lbl_owner")
        self.horizontalLayout_3.addWidget(self.lbl_owner)
        spacerItem1 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lyt_vert_filter_owner.addLayout(self.horizontalLayout_3)
        self.cbb_format = QtWidgets.QComboBox(self.grp_filters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_format.sizePolicy().hasHeightForWidth())
        self.cbb_format.setSizePolicy(sizePolicy)
        self.cbb_format.setMinimumSize(QtCore.QSize(250, 25))
        self.cbb_format.setMaximumSize(QtCore.QSize(350, 35))
        self.cbb_format.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_format.setAutoFillBackground(True)
        self.cbb_format.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbb_format.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbb_format.setMinimumContentsLength(50)
        self.cbb_format.setObjectName("cbb_format")
        self.lyt_vert_filter_owner.addWidget(self.cbb_format)
        self.lyt_vert_filters_left.addLayout(self.lyt_vert_filter_owner)
        self.lyt_advc_search.addLayout(self.lyt_vert_filters_left)
        self.lyt_vert_filters_right = QtWidgets.QVBoxLayout()
        self.lyt_vert_filters_right.setObjectName("lyt_vert_filters_right")
        self.lyt_vert_filter_type = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_type.setObjectName("lyt_vert_filter_type")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ico_type = QtWidgets.QLabel(self.grp_filters)
        self.ico_type.setMaximumSize(QtCore.QSize(18, 18))
        self.ico_type.setText("")
        self.ico_type.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/asterisk.svg"))
        self.ico_type.setScaledContents(True)
        self.ico_type.setObjectName("ico_type")
        self.horizontalLayout_2.addWidget(self.ico_type)
        self.lbl_type = QtWidgets.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_type.setFont(font)
        self.lbl_type.setObjectName("lbl_type")
        self.horizontalLayout_2.addWidget(self.lbl_type)
        spacerItem2 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lyt_vert_filter_type.addLayout(self.horizontalLayout_2)
        self.cbb_type = QtWidgets.QComboBox(self.grp_filters)
        self.cbb_type.setMinimumSize(QtCore.QSize(250, 25))
        self.cbb_type.setMaximumSize(QtCore.QSize(350, 35))
        self.cbb_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_type.setAutoFillBackground(True)
        self.cbb_type.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbb_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbb_type.setMinimumContentsLength(50)
        self.cbb_type.setObjectName("cbb_type")
        self.lyt_vert_filter_type.addWidget(self.cbb_type)
        self.lyt_vert_filters_right.addLayout(self.lyt_vert_filter_type)
        self.lyt_vert_filter_keyword = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_keyword.setObjectName("lyt_vert_filter_keyword")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ico_keyword = QtWidgets.QLabel(self.grp_filters)
        self.ico_keyword.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ico_keyword.setFont(font)
        self.ico_keyword.setText("")
        self.ico_keyword.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/tag.svg"))
        self.ico_keyword.setScaledContents(True)
        self.ico_keyword.setObjectName("ico_keyword")
        self.horizontalLayout_5.addWidget(self.ico_keyword)
        self.lbl_keyword = QtWidgets.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_keyword.setFont(font)
        self.lbl_keyword.setObjectName("lbl_keyword")
        self.horizontalLayout_5.addWidget(self.lbl_keyword)
        spacerItem3 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lyt_vert_filter_keyword.addLayout(self.horizontalLayout_5)
        self.cbb_keyword = QtWidgets.QComboBox(self.grp_filters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_keyword.sizePolicy().hasHeightForWidth())
        self.cbb_keyword.setSizePolicy(sizePolicy)
        self.cbb_keyword.setMinimumSize(QtCore.QSize(250, 25))
        self.cbb_keyword.setMaximumSize(QtCore.QSize(350, 35))
        self.cbb_keyword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_keyword.setAutoFillBackground(True)
        self.cbb_keyword.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbb_keyword.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbb_keyword.setMinimumContentsLength(50)
        self.cbb_keyword.setObjectName("cbb_keyword")
        self.lyt_vert_filter_keyword.addWidget(self.cbb_keyword)
        self.lyt_vert_filters_right.addLayout(self.lyt_vert_filter_keyword)
        self.lyt_advc_search.addLayout(self.lyt_vert_filters_right)
        self.gridLayout_3.addLayout(self.lyt_advc_search, 0, 1, 1, 1)
        self.btn_reinit = QtWidgets.QPushButton(self.grp_filters)
        self.btn_reinit.setMinimumSize(QtCore.QSize(33, 30))
        self.btn_reinit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_reinit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reinit.setAutoFillBackground(True)
        self.btn_reinit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reinit.setIcon(icon1)
        self.btn_reinit.setIconSize(QtCore.QSize(18, 18))
        self.btn_reinit.setAutoDefault(False)
        self.btn_reinit.setDefault(False)
        self.btn_reinit.setFlat(False)
        self.btn_reinit.setObjectName("btn_reinit")
        self.gridLayout_3.addWidget(self.btn_reinit, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.grp_filters)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Export)
        self.groupBox_2.setMinimumSize(QtCore.QSize(550, 150))
        self.groupBox_2.setMaximumSize(QtCore.QSize(600, 200))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lyt_exports_formats_selection = QtWidgets.QHBoxLayout()
        self.lyt_exports_formats_selection.setObjectName("lyt_exports_formats_selection")
        self.Excel = QtWidgets.QGroupBox(self.groupBox_2)
        self.Excel.setMinimumSize(QtCore.QSize(50, 100))
        self.Excel.setMaximumSize(QtCore.QSize(175, 150))
        self.Excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Excel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Excel.setAutoFillBackground(True)
        self.Excel.setTitle("Excel")
        self.Excel.setCheckable(True)
        self.Excel.setObjectName("Excel")
        self.ico_excel = QtWidgets.QLabel(self.Excel)
        self.ico_excel.setGeometry(QtCore.QRect(50, 30, 100, 100))
        self.ico_excel.setMinimumSize(QtCore.QSize(32, 32))
        self.ico_excel.setMaximumSize(QtCore.QSize(100, 100))
        self.ico_excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ico_excel.setText("")
        self.ico_excel.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/excel.svg"))
        self.ico_excel.setScaledContents(True)
        self.ico_excel.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_excel.setWordWrap(False)
        self.ico_excel.setIndent(-2)
        self.ico_excel.setObjectName("ico_excel")
        self.lyt_exports_formats_selection.addWidget(self.Excel)
        self.Word = QtWidgets.QGroupBox(self.groupBox_2)
        self.Word.setMinimumSize(QtCore.QSize(50, 100))
        self.Word.setMaximumSize(QtCore.QSize(175, 150))
        self.Word.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Word.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Word.setAutoFillBackground(True)
        self.Word.setTitle("Word")
        self.Word.setCheckable(True)
        self.Word.setObjectName("Word")
        self.ico_word = QtWidgets.QLabel(self.Word)
        self.ico_word.setGeometry(QtCore.QRect(60, 30, 100, 100))
        self.ico_word.setMinimumSize(QtCore.QSize(32, 32))
        self.ico_word.setMaximumSize(QtCore.QSize(100, 100))
        self.ico_word.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ico_word.setText("")
        self.ico_word.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/word.svg"))
        self.ico_word.setScaledContents(True)
        self.ico_word.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_word.setWordWrap(False)
        self.ico_word.setIndent(-2)
        self.ico_word.setObjectName("ico_word")
        self.lyt_exports_formats_selection.addWidget(self.Word)
        self.XML = QtWidgets.QGroupBox(self.groupBox_2)
        self.XML.setMinimumSize(QtCore.QSize(50, 100))
        self.XML.setMaximumSize(QtCore.QSize(175, 150))
        self.XML.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.XML.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.XML.setAutoFillBackground(True)
        self.XML.setTitle("XML ISO 19139")
        self.XML.setCheckable(True)
        self.XML.setObjectName("XML")
        self.ico_xml = QtWidgets.QLabel(self.XML)
        self.ico_xml.setGeometry(QtCore.QRect(50, 30, 100, 100))
        self.ico_xml.setMinimumSize(QtCore.QSize(32, 32))
        self.ico_xml.setMaximumSize(QtCore.QSize(100, 100))
        self.ico_xml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ico_xml.setText("")
        self.ico_xml.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/xml.svg"))
        self.ico_xml.setScaledContents(True)
        self.ico_xml.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_xml.setWordWrap(False)
        self.ico_xml.setIndent(-2)
        self.ico_xml.setObjectName("ico_xml")
        self.lyt_exports_formats_selection.addWidget(self.XML)
        self.verticalLayout.addLayout(self.lyt_exports_formats_selection)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.btn_launch_export = QtWidgets.QPushButton(self.Export)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_launch_export.sizePolicy().hasHeightForWidth())
        self.btn_launch_export.setSizePolicy(sizePolicy)
        self.btn_launch_export.setMinimumSize(QtCore.QSize(201, 0))
        self.btn_launch_export.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_launch_export.setFont(font)
        self.btn_launch_export.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/rocket.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_launch_export.setIcon(icon2)
        self.btn_launch_export.setAutoDefault(True)
        self.btn_launch_export.setDefault(True)
        self.btn_launch_export.setObjectName("btn_launch_export")
        self.verticalLayout_2.addWidget(self.btn_launch_export)
        self.pgb_exports = QtWidgets.QProgressBar(self.Export)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pgb_exports.sizePolicy().hasHeightForWidth())
        self.pgb_exports.setSizePolicy(sizePolicy)
        self.pgb_exports.setAutoFillBackground(True)
        self.pgb_exports.setProperty("value", 10)
        self.pgb_exports.setTextVisible(False)
        self.pgb_exports.setInvertedAppearance(False)
        self.pgb_exports.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pgb_exports.setObjectName("pgb_exports")
        self.verticalLayout_2.addWidget(self.pgb_exports)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs_IsogeoToOffice.addTab(self.Export, icon3, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setAutoFillBackground(True)
        self.Settings.setObjectName("Settings")
        self.groupBox_ressources = QtWidgets.QGroupBox(self.Settings)
        self.groupBox_ressources.setGeometry(QtCore.QRect(20, 560, 751, 149))
        self.groupBox_ressources.setObjectName("groupBox_ressources")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_ressources)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lbl_report = QtWidgets.QLabel(self.groupBox_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_report.setFont(font)
        self.lbl_report.setObjectName("lbl_report")
        self.horizontalLayout_24.addWidget(self.lbl_report)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.btn_log_dir = QtWidgets.QPushButton(self.groupBox_ressources)
        self.btn_log_dir.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_log_dir.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_log_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_log_dir.setAutoFillBackground(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/folder-open-o.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_log_dir.setIcon(icon4)
        self.btn_log_dir.setObjectName("btn_log_dir")
        self.horizontalLayout_24.addWidget(self.btn_log_dir)
        self.btn_report = QtWidgets.QPushButton(self.groupBox_ressources)
        self.btn_report.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_report.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_report.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_report.setAutoFillBackground(True)
        self.btn_report.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/bullhorn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_report.setIcon(icon5)
        self.btn_report.setObjectName("btn_report")
        self.horizontalLayout_24.addWidget(self.btn_report)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lbl_help = QtWidgets.QLabel(self.groupBox_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_help.setFont(font)
        self.lbl_help.setObjectName("lbl_help")
        self.horizontalLayout_23.addWidget(self.lbl_help)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem5)
        self.btn_help = QtWidgets.QPushButton(self.groupBox_ressources)
        self.btn_help.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_help.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_help.setAutoFillBackground(True)
        self.btn_help.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/question.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_help.setIcon(icon6)
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout_23.addWidget(self.btn_help)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lbl_credits = QtWidgets.QLabel(self.groupBox_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_credits.setFont(font)
        self.lbl_credits.setObjectName("lbl_credits")
        self.horizontalLayout_22.addWidget(self.lbl_credits)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.btn_credits = QtWidgets.QPushButton(self.groupBox_ressources)
        self.btn_credits.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_credits.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_credits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_credits.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_credits.setIcon(icon7)
        self.btn_credits.setObjectName("btn_credits")
        self.horizontalLayout_22.addWidget(self.btn_credits)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.groupBox_auth = QtWidgets.QGroupBox(self.Settings)
        self.groupBox_auth.setGeometry(QtCore.QRect(20, 310, 751, 241))
        self.groupBox_auth.setObjectName("groupBox_auth")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_auth)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txt_shares = QtWidgets.QTextBrowser(self.groupBox_auth)
        self.txt_shares.setObjectName("txt_shares")
        self.gridLayout_5.addWidget(self.txt_shares, 1, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbl_auth = QtWidgets.QLabel(self.groupBox_auth)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_auth.setFont(font)
        self.lbl_auth.setObjectName("lbl_auth")
        self.horizontalLayout_21.addWidget(self.lbl_auth)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem7)
        self.btn_change_user = QtWidgets.QPushButton(self.groupBox_auth)
        self.btn_change_user.setMinimumSize(QtCore.QSize(91, 24))
        self.btn_change_user.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_change_user.setIcon(icon8)
        self.btn_change_user.setObjectName("btn_change_user")
        self.horizontalLayout_21.addWidget(self.btn_change_user)
        self.gridLayout_5.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.Settings)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 751, 271))
        self.groupBox.setMinimumSize(QtCore.QSize(751, 271))
        self.groupBox.setObjectName("groupBox")
        self.lbl_output_directory_name = QtWidgets.QLabel(self.groupBox)
        self.lbl_output_directory_name.setGeometry(QtCore.QRect(20, 40, 111, 31))
        self.lbl_output_directory_name.setObjectName("lbl_output_directory_name")
        self.txt_uid = QtWidgets.QLineEdit(self.groupBox)
        self.txt_uid.setGeometry(QtCore.QRect(670, 200, 61, 30))
        self.txt_uid.setMinimumSize(QtCore.QSize(20, 30))
        self.txt_uid.setAutoFillBackground(True)
        self.txt_uid.setInputMask("")
        self.txt_uid.setText("")
        self.txt_uid.setObjectName("txt_uid")
        self.lbl_timestamp = QtWidgets.QLabel(self.groupBox)
        self.lbl_timestamp.setGeometry(QtCore.QRect(20, 200, 131, 31))
        self.lbl_timestamp.setObjectName("lbl_timestamp")
        self.lbl_uid = QtWidgets.QLabel(self.groupBox)
        self.lbl_uid.setGeometry(QtCore.QRect(540, 200, 111, 31))
        self.lbl_uid.setObjectName("lbl_uid")
        self.cbb_timestamp = QtWidgets.QComboBox(self.groupBox)
        self.cbb_timestamp.setGeometry(QtCore.QRect(180, 200, 261, 31))
        self.cbb_timestamp.setObjectName("cbb_timestamp")
        self.checkBox_zip_xml = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_zip_xml.setGeometry(QtCore.QRect(530, 150, 16, 21))
        self.checkBox_zip_xml.setText("")
        self.checkBox_zip_xml.setObjectName("checkBox_zip_xml")
        self.lbl_zip = QtWidgets.QLabel(self.groupBox)
        self.lbl_zip.setGeometry(QtCore.QRect(560, 150, 151, 31))
        self.lbl_zip.setObjectName("lbl_zip")
        self.checkBox_display_att_occ = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_display_att_occ.setGeometry(QtCore.QRect(280, 150, 16, 21))
        self.checkBox_display_att_occ.setObjectName("checkBox_display_att_occ")
        self.lbl_display_att_occ = QtWidgets.QLabel(self.groupBox)
        self.lbl_display_att_occ.setGeometry(QtCore.QRect(310, 150, 171, 31))
        self.lbl_display_att_occ.setObjectName("lbl_display_att_occ")
        self.lbl_display_cat_ind = QtWidgets.QLabel(self.groupBox)
        self.lbl_display_cat_ind.setGeometry(QtCore.QRect(80, 150, 151, 31))
        self.lbl_display_cat_ind.setObjectName("lbl_display_cat_ind")
        self.checkBox_display_cat_ind = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_display_cat_ind.setGeometry(QtCore.QRect(50, 150, 16, 21))
        self.checkBox_display_cat_ind.setText("")
        self.checkBox_display_cat_ind.setObjectName("checkBox_display_cat_ind")
        self.txt_output_fileprefix = QtWidgets.QLineEdit(self.groupBox)
        self.txt_output_fileprefix.setGeometry(QtCore.QRect(170, 90, 521, 30))
        self.txt_output_fileprefix.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_output_fileprefix.setAutoFillBackground(True)
        self.txt_output_fileprefix.setInputMask("")
        self.txt_output_fileprefix.setText("")
        self.txt_output_fileprefix.setObjectName("txt_output_fileprefix")
        self.lbl_output_fileprefix = QtWidgets.QLabel(self.groupBox)
        self.lbl_output_fileprefix.setGeometry(QtCore.QRect(20, 90, 111, 31))
        self.lbl_output_fileprefix.setObjectName("lbl_output_fileprefix")
        self.lbl_directory_name = QtWidgets.QLabel(self.groupBox)
        self.lbl_directory_name.setGeometry(QtCore.QRect(170, 40, 521, 29))
        self.lbl_directory_name.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbl_directory_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_directory_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_directory_name.setObjectName("lbl_directory_name")
        self.btn_directory_change = QtWidgets.QToolButton(self.groupBox)
        self.btn_directory_change.setGeometry(QtCore.QRect(700, 40, 31, 31))
        self.btn_directory_change.setText("...")
        self.btn_directory_change.setObjectName("btn_directory_change")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/gear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs_IsogeoToOffice.addTab(self.Settings, icon9, "")

        self.retranslateUi(tabs_IsogeoToOffice)
        tabs_IsogeoToOffice.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabs_IsogeoToOffice)

    def retranslateUi(self, tabs_IsogeoToOffice):
        _translate = QtCore.QCoreApplication.translate
        self.grp_filters.setTitle(_translate("tabs_IsogeoToOffice", "Filters"))
        self.lbl_share.setText(_translate("tabs_IsogeoToOffice", "Share"))
        self.lbl_owner.setText(_translate("tabs_IsogeoToOffice", "Metadata Owner"))
        self.lbl_type.setText(_translate("tabs_IsogeoToOffice", "Resource type"))
        self.lbl_keyword.setText(_translate("tabs_IsogeoToOffice", "Keyword"))
        self.btn_reinit.setToolTip(_translate("tabs_IsogeoToOffice", "Reset search form"))
        self.groupBox_2.setTitle(_translate("tabs_IsogeoToOffice", "Output formats"))
        self.btn_launch_export.setToolTip(_translate("tabs_IsogeoToOffice", "Launch export"))
        self.btn_launch_export.setText(_translate("tabs_IsogeoToOffice", "Launch export"))
        tabs_IsogeoToOffice.setTabText(tabs_IsogeoToOffice.indexOf(self.Export), _translate("tabs_IsogeoToOffice", "Export"))
        self.groupBox_ressources.setTitle(_translate("tabs_IsogeoToOffice", "Resources"))
        self.lbl_report.setText(_translate("tabs_IsogeoToOffice", "Report an issue on the bug tracker"))
        self.btn_log_dir.setToolTip(_translate("tabs_IsogeoToOffice", "Get the log file: \"log_isogeo_isogeo2office.log\""))
        self.btn_log_dir.setText(_translate("tabs_IsogeoToOffice", "LOG File"))
        self.lbl_help.setText(_translate("tabs_IsogeoToOffice", "Open online application help"))
        self.btn_help.setToolTip(_translate("tabs_IsogeoToOffice", "Open online help in default browser"))
        self.lbl_credits.setText(_translate("tabs_IsogeoToOffice", "Open application credits"))
        self.btn_credits.setToolTip(_translate("tabs_IsogeoToOffice", "Open credits popup"))
        self.groupBox_auth.setTitle(_translate("tabs_IsogeoToOffice", "Authentication settings"))
        self.lbl_auth.setText(_translate("tabs_IsogeoToOffice", "Set application authentication:"))
        self.groupBox.setTitle(_translate("tabs_IsogeoToOffice", "Export settings"))
        self.lbl_output_directory_name.setText(_translate("tabs_IsogeoToOffice", "Output repository:"))
        self.txt_uid.setToolTip(_translate("tabs_IsogeoToOffice", "Enter output file name"))
        self.txt_uid.setPlaceholderText(_translate("tabs_IsogeoToOffice", "5"))
        self.lbl_timestamp.setText(_translate("tabs_IsogeoToOffice", "Display Timestamp:"))
        self.lbl_uid.setText(_translate("tabs_IsogeoToOffice", "UID chars [0 - 8]: "))
        self.checkBox_zip_xml.setToolTip(_translate("tabs_IsogeoToOffice", "Export metadata in XML ISO 19139"))
        self.lbl_zip.setText(_translate("tabs_IsogeoToOffice", "Pack all XML into one .zip"))
        self.checkBox_display_att_occ.setToolTip(_translate("tabs_IsogeoToOffice", "Export metadata in XML ISO 19139"))
        self.checkBox_display_att_occ.setText(_translate("tabs_IsogeoToOffice", "Display attributes ocurrences :"))
        self.lbl_display_att_occ.setText(_translate("tabs_IsogeoToOffice", "Display attributs occurrence"))
        self.lbl_display_cat_ind.setText(_translate("tabs_IsogeoToOffice", "Display catalog indicators"))
        self.checkBox_display_cat_ind.setToolTip(_translate("tabs_IsogeoToOffice", "Export metadata in XML ISO 19139"))
        self.txt_output_fileprefix.setToolTip(_translate("tabs_IsogeoToOffice", "Enter output file name"))
        self.txt_output_fileprefix.setPlaceholderText(_translate("tabs_IsogeoToOffice", "isogeo2office"))
        self.lbl_output_fileprefix.setText(_translate("tabs_IsogeoToOffice", "Output fileprefix:"))
        self.lbl_directory_name.setText(_translate("tabs_IsogeoToOffice", "Output"))
        tabs_IsogeoToOffice.setTabText(tabs_IsogeoToOffice.indexOf(self.Settings), _translate("tabs_IsogeoToOffice", "Settings"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabs_IsogeoToOffice = QtWidgets.QTabWidget()
    ui = Ui_tabs_IsogeoToOffice()
    ui.setupUi(tabs_IsogeoToOffice)
    tabs_IsogeoToOffice.show()
    sys.exit(app.exec_())

