# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\modules\ui\main\ui_win_IsogeoToOffice.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_win_IsogeoToOffice(object):
    def setupUi(self, win_IsogeoToOffice):
        win_IsogeoToOffice.setObjectName("win_IsogeoToOffice")
        win_IsogeoToOffice.resize(643, 853)
        win_IsogeoToOffice.setMinimumSize(QtCore.QSize(643, 795))
        win_IsogeoToOffice.setMaximumSize(QtCore.QSize(643, 853))
        win_IsogeoToOffice.setWindowTitle("Isogeo To Office")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_IsogeoToOffice.setWindowIcon(icon)
        win_IsogeoToOffice.setToolTip("")
        win_IsogeoToOffice.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        win_IsogeoToOffice.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        win_IsogeoToOffice.setTabShape(QtWidgets.QTabWidget.Rounded)
        win_IsogeoToOffice.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks)
        win_IsogeoToOffice.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(win_IsogeoToOffice)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_3.setObjectName("formLayout_3")
        self.tabs_IsogeoToOffice = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs_IsogeoToOffice.setMinimumSize(QtCore.QSize(500, 0))
        self.tabs_IsogeoToOffice.setMaximumSize(QtCore.QSize(800, 1500))
        self.tabs_IsogeoToOffice.setDocumentMode(True)
        self.tabs_IsogeoToOffice.setObjectName("tabs_IsogeoToOffice")
        self.tab_export = QtWidgets.QWidget()
        self.tab_export.setObjectName("tab_export")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_export)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grp_filters = QtWidgets.QGroupBox(self.tab_export)
        self.grp_filters.setMinimumSize(QtCore.QSize(550, 150))
        self.grp_filters.setMaximumSize(QtCore.QSize(600, 200))
        self.grp_filters.setAutoFillBackground(False)
        self.grp_filters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.grp_filters.setObjectName("grp_filters")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.grp_filters)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_reinit = QtWidgets.QPushButton(self.grp_filters)
        self.btn_reinit.setMinimumSize(QtCore.QSize(33, 30))
        self.btn_reinit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_reinit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reinit.setAutoFillBackground(True)
        self.btn_reinit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reinit.setIcon(icon1)
        self.btn_reinit.setIconSize(QtCore.QSize(18, 18))
        self.btn_reinit.setAutoDefault(False)
        self.btn_reinit.setDefault(False)
        self.btn_reinit.setFlat(False)
        self.btn_reinit.setObjectName("btn_reinit")
        self.gridLayout_5.addWidget(self.btn_reinit, 2, 1, 1, 1)
        self.lyt_advc_search = QtWidgets.QHBoxLayout()
        self.lyt_advc_search.setObjectName("lyt_advc_search")
        self.lyt_vert_filters_left = QtWidgets.QVBoxLayout()
        self.lyt_vert_filters_left.setObjectName("lyt_vert_filters_left")
        self.lyt_vert_share = QtWidgets.QVBoxLayout()
        self.lyt_vert_share.setObjectName("lyt_vert_share")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ico_share = QtWidgets.QLabel(self.grp_filters)
        self.ico_share.setMaximumSize(QtCore.QSize(18, 18))
        self.ico_share.setText("")
        self.ico_share.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/share-alt.svg"))
        self.ico_share.setScaledContents(True)
        self.ico_share.setObjectName("ico_share")
        self.horizontalLayout_4.addWidget(self.ico_share)
        self.lbl_share = QtWidgets.QLabel(self.grp_filters)
        self.lbl_share.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_share.setFont(font)
        self.lbl_share.setObjectName("lbl_share")
        self.horizontalLayout_4.addWidget(self.lbl_share)
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lyt_vert_share.addLayout(self.horizontalLayout_4)
        self.cbb_share = QtWidgets.QComboBox(self.grp_filters)
        self.cbb_share.setMinimumSize(QtCore.QSize(250, 25))
        self.cbb_share.setMaximumSize(QtCore.QSize(350, 35))
        self.cbb_share.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_share.setAutoFillBackground(True)
        self.cbb_share.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbb_share.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbb_share.setMinimumContentsLength(50)
        self.cbb_share.setObjectName("cbb_share")
        self.lyt_vert_share.addWidget(self.cbb_share)
        self.lyt_vert_filters_left.addLayout(self.lyt_vert_share)
        self.lyt_vert_filter_owner = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_owner.setObjectName("lyt_vert_filter_owner")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ico_owner = QtWidgets.QLabel(self.grp_filters)
        self.ico_owner.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ico_owner.setFont(font)
        self.ico_owner.setText("")
        self.ico_owner.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/users.svg"))
        self.ico_owner.setScaledContents(True)
        self.ico_owner.setObjectName("ico_owner")
        self.horizontalLayout_6.addWidget(self.ico_owner)
        self.lbl_owner = QtWidgets.QLabel(self.grp_filters)
        self.lbl_owner.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_owner.setFont(font)
        self.lbl_owner.setObjectName("lbl_owner")
        self.horizontalLayout_6.addWidget(self.lbl_owner)
        spacerItem1 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.lyt_vert_filter_owner.addLayout(self.horizontalLayout_6)
        self.cbb_owner = QtWidgets.QComboBox(self.grp_filters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_owner.sizePolicy().hasHeightForWidth())
        self.cbb_owner.setSizePolicy(sizePolicy)
        self.cbb_owner.setMinimumSize(QtCore.QSize(250, 25))
        self.cbb_owner.setMaximumSize(QtCore.QSize(350, 35))
        self.cbb_owner.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_owner.setAutoFillBackground(True)
        self.cbb_owner.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbb_owner.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbb_owner.setMinimumContentsLength(50)
        self.cbb_owner.setObjectName("cbb_owner")
        self.lyt_vert_filter_owner.addWidget(self.cbb_owner)
        self.lyt_vert_filters_left.addLayout(self.lyt_vert_filter_owner)
        self.lyt_advc_search.addLayout(self.lyt_vert_filters_left)
        self.lyt_vert_filters_right = QtWidgets.QVBoxLayout()
        self.lyt_vert_filters_right.setObjectName("lyt_vert_filters_right")
        self.lyt_vert_filter_type = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_type.setObjectName("lyt_vert_filter_type")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ico_type = QtWidgets.QLabel(self.grp_filters)
        self.ico_type.setMaximumSize(QtCore.QSize(18, 18))
        self.ico_type.setText("")
        self.ico_type.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/asterisk.svg"))
        self.ico_type.setScaledContents(True)
        self.ico_type.setObjectName("ico_type")
        self.horizontalLayout_7.addWidget(self.ico_type)
        self.lbl_type = QtWidgets.QLabel(self.grp_filters)
        self.lbl_type.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_type.setFont(font)
        self.lbl_type.setObjectName("lbl_type")
        self.horizontalLayout_7.addWidget(self.lbl_type)
        spacerItem2 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.lyt_vert_filter_type.addLayout(self.horizontalLayout_7)
        self.cbb_type = QtWidgets.QComboBox(self.grp_filters)
        self.cbb_type.setMinimumSize(QtCore.QSize(250, 25))
        self.cbb_type.setMaximumSize(QtCore.QSize(350, 35))
        self.cbb_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_type.setAutoFillBackground(True)
        self.cbb_type.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbb_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbb_type.setMinimumContentsLength(50)
        self.cbb_type.setObjectName("cbb_type")
        self.lyt_vert_filter_type.addWidget(self.cbb_type)
        self.lyt_vert_filters_right.addLayout(self.lyt_vert_filter_type)
        self.lyt_vert_filter_keyword = QtWidgets.QVBoxLayout()
        self.lyt_vert_filter_keyword.setObjectName("lyt_vert_filter_keyword")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ico_keyword = QtWidgets.QLabel(self.grp_filters)
        self.ico_keyword.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ico_keyword.setFont(font)
        self.ico_keyword.setText("")
        self.ico_keyword.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/tag.svg"))
        self.ico_keyword.setScaledContents(True)
        self.ico_keyword.setObjectName("ico_keyword")
        self.horizontalLayout_8.addWidget(self.ico_keyword)
        self.lbl_keyword = QtWidgets.QLabel(self.grp_filters)
        self.lbl_keyword.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_keyword.setFont(font)
        self.lbl_keyword.setObjectName("lbl_keyword")
        self.horizontalLayout_8.addWidget(self.lbl_keyword)
        spacerItem3 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.lyt_vert_filter_keyword.addLayout(self.horizontalLayout_8)
        self.cbb_keyword = QtWidgets.QComboBox(self.grp_filters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_keyword.sizePolicy().hasHeightForWidth())
        self.cbb_keyword.setSizePolicy(sizePolicy)
        self.cbb_keyword.setMinimumSize(QtCore.QSize(250, 25))
        self.cbb_keyword.setMaximumSize(QtCore.QSize(350, 35))
        self.cbb_keyword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbb_keyword.setAutoFillBackground(True)
        self.cbb_keyword.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbb_keyword.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbb_keyword.setMinimumContentsLength(50)
        self.cbb_keyword.setObjectName("cbb_keyword")
        self.lyt_vert_filter_keyword.addWidget(self.cbb_keyword)
        self.lyt_vert_filters_right.addLayout(self.lyt_vert_filter_keyword)
        self.lyt_advc_search.addLayout(self.lyt_vert_filters_right)
        self.gridLayout_5.addLayout(self.lyt_advc_search, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.grp_filters)
        self.grp_formats = QtWidgets.QGroupBox(self.tab_export)
        self.grp_formats.setMinimumSize(QtCore.QSize(550, 200))
        self.grp_formats.setMaximumSize(QtCore.QSize(600, 200))
        self.grp_formats.setAutoFillBackground(False)
        self.grp_formats.setObjectName("grp_formats")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grp_formats)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lyt_exports_formats_selection = QtWidgets.QHBoxLayout()
        self.lyt_exports_formats_selection.setObjectName("lyt_exports_formats_selection")
        self.chb_output_excel = QtWidgets.QGroupBox(self.grp_formats)
        self.chb_output_excel.setMinimumSize(QtCore.QSize(50, 100))
        self.chb_output_excel.setMaximumSize(QtCore.QSize(200, 150))
        self.chb_output_excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chb_output_excel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.chb_output_excel.setAutoFillBackground(False)
        self.chb_output_excel.setTitle("Excel")
        self.chb_output_excel.setCheckable(True)
        self.chb_output_excel.setObjectName("chb_output_excel")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.chb_output_excel)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ico_excel = QtWidgets.QLabel(self.chb_output_excel)
        self.ico_excel.setMinimumSize(QtCore.QSize(32, 32))
        self.ico_excel.setMaximumSize(QtCore.QSize(100, 100))
        self.ico_excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ico_excel.setText("")
        self.ico_excel.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/excel.svg"))
        self.ico_excel.setScaledContents(True)
        self.ico_excel.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_excel.setWordWrap(False)
        self.ico_excel.setIndent(-2)
        self.ico_excel.setObjectName("ico_excel")
        self.gridLayout_6.addWidget(self.ico_excel, 0, 0, 1, 1)
        self.lyt_exports_formats_selection.addWidget(self.chb_output_excel)
        self.chb_output_word = QtWidgets.QGroupBox(self.grp_formats)
        self.chb_output_word.setMinimumSize(QtCore.QSize(50, 150))
        self.chb_output_word.setMaximumSize(QtCore.QSize(200, 150))
        self.chb_output_word.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chb_output_word.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.chb_output_word.setAutoFillBackground(False)
        self.chb_output_word.setTitle("Word")
        self.chb_output_word.setFlat(False)
        self.chb_output_word.setCheckable(True)
        self.chb_output_word.setObjectName("chb_output_word")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.chb_output_word)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ico_word = QtWidgets.QLabel(self.chb_output_word)
        self.ico_word.setMinimumSize(QtCore.QSize(32, 32))
        self.ico_word.setMaximumSize(QtCore.QSize(100, 100))
        self.ico_word.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ico_word.setText("")
        self.ico_word.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/word.svg"))
        self.ico_word.setScaledContents(True)
        self.ico_word.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_word.setWordWrap(False)
        self.ico_word.setIndent(-2)
        self.ico_word.setObjectName("ico_word")
        self.gridLayout_8.addWidget(self.ico_word, 0, 0, 1, 1)
        self.lyt_exports_formats_selection.addWidget(self.chb_output_word)
        self.chb_output_xml = QtWidgets.QGroupBox(self.grp_formats)
        self.chb_output_xml.setMinimumSize(QtCore.QSize(50, 100))
        self.chb_output_xml.setMaximumSize(QtCore.QSize(200, 150))
        self.chb_output_xml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chb_output_xml.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.chb_output_xml.setAutoFillBackground(False)
        self.chb_output_xml.setTitle("XML ISO 19139")
        self.chb_output_xml.setCheckable(True)
        self.chb_output_xml.setObjectName("chb_output_xml")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.chb_output_xml)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ico_xml = QtWidgets.QLabel(self.chb_output_xml)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ico_xml.sizePolicy().hasHeightForWidth())
        self.ico_xml.setSizePolicy(sizePolicy)
        self.ico_xml.setMinimumSize(QtCore.QSize(32, 32))
        self.ico_xml.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.ico_xml.setFont(font)
        self.ico_xml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ico_xml.setText("")
        self.ico_xml.setPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/xml.svg"))
        self.ico_xml.setScaledContents(True)
        self.ico_xml.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_xml.setWordWrap(True)
        self.ico_xml.setIndent(-2)
        self.ico_xml.setObjectName("ico_xml")
        self.gridLayout_9.addWidget(self.ico_xml, 0, 0, 1, 1)
        self.lyt_exports_formats_selection.addWidget(self.chb_output_xml)
        self.verticalLayout_2.addLayout(self.lyt_exports_formats_selection)
        self.verticalLayout_3.addWidget(self.grp_formats)
        self.btn_launch_export = QtWidgets.QPushButton(self.tab_export)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_launch_export.sizePolicy().hasHeightForWidth())
        self.btn_launch_export.setSizePolicy(sizePolicy)
        self.btn_launch_export.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_launch_export.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_launch_export.setFont(font)
        self.btn_launch_export.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/rocket.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_launch_export.setIcon(icon2)
        self.btn_launch_export.setAutoDefault(True)
        self.btn_launch_export.setDefault(True)
        self.btn_launch_export.setObjectName("btn_launch_export")
        self.verticalLayout_3.addWidget(self.btn_launch_export)
        spacerItem5 = QtWidgets.QSpacerItem(20, 286, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/export/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs_IsogeoToOffice.addTab(self.tab_export, icon3, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_settings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.grp_preferences = QtWidgets.QGroupBox(self.tab_settings)
        self.grp_preferences.setMinimumSize(QtCore.QSize(550, 350))
        self.grp_preferences.setMaximumSize(QtCore.QSize(600, 450))
        self.grp_preferences.setAutoFillBackground(False)
        self.grp_preferences.setObjectName("grp_preferences")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grp_preferences)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tlb_settings = QtWidgets.QToolBox(self.grp_preferences)
        self.tlb_settings.setMinimumSize(QtCore.QSize(450, 250))
        self.tlb_settings.setMaximumSize(QtCore.QSize(600, 500))
        self.tlb_settings.setObjectName("tlb_settings")
        self.tlb_section_global = QtWidgets.QWidget()
        self.tlb_section_global.setGeometry(QtCore.QRect(0, 0, 580, 197))
        self.tlb_section_global.setMinimumSize(QtCore.QSize(3, 0))
        self.tlb_section_global.setMaximumSize(QtCore.QSize(600, 200))
        self.tlb_section_global.setObjectName("tlb_section_global")
        self.gridLayout = QtWidgets.QGridLayout(self.tlb_section_global)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_timestamp = QtWidgets.QLabel(self.tlb_section_global)
        self.lbl_timestamp.setMinimumSize(QtCore.QSize(100, 20))
        self.lbl_timestamp.setMaximumSize(QtCore.QSize(200, 25))
        self.lbl_timestamp.setObjectName("lbl_timestamp")
        self.gridLayout.addWidget(self.lbl_timestamp, 2, 0, 1, 1)
        self.cbb_timestamp = QtWidgets.QComboBox(self.tlb_section_global)
        self.cbb_timestamp.setMinimumSize(QtCore.QSize(150, 25))
        self.cbb_timestamp.setMaximumSize(QtCore.QSize(250, 35))
        self.cbb_timestamp.setObjectName("cbb_timestamp")
        self.cbb_timestamp.addItem("")
        self.cbb_timestamp.addItem("")
        self.cbb_timestamp.addItem("")
        self.gridLayout.addWidget(self.cbb_timestamp, 2, 2, 1, 2)
        self.lbl_output_folder_value = QtWidgets.QLabel(self.tlb_section_global)
        self.lbl_output_folder_value.setMinimumSize(QtCore.QSize(150, 20))
        self.lbl_output_folder_value.setMaximumSize(QtCore.QSize(250, 35))
        self.lbl_output_folder_value.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbl_output_folder_value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_output_folder_value.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_output_folder_value.setScaledContents(False)
        self.lbl_output_folder_value.setObjectName("lbl_output_folder_value")
        self.gridLayout.addWidget(self.lbl_output_folder_value, 1, 2, 1, 1)
        self.txt_output_fileprefix = QtWidgets.QLineEdit(self.tlb_section_global)
        self.txt_output_fileprefix.setMinimumSize(QtCore.QSize(200, 20))
        self.txt_output_fileprefix.setMaximumSize(QtCore.QSize(300, 35))
        self.txt_output_fileprefix.setAutoFillBackground(True)
        self.txt_output_fileprefix.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_output_fileprefix.setInputMask("")
        self.txt_output_fileprefix.setMaxLength(25)
        self.txt_output_fileprefix.setClearButtonEnabled(True)
        self.txt_output_fileprefix.setObjectName("txt_output_fileprefix")
        self.gridLayout.addWidget(self.txt_output_fileprefix, 5, 2, 1, 1)
        self.lbl_uid = QtWidgets.QLabel(self.tlb_section_global)
        self.lbl_uid.setMinimumSize(QtCore.QSize(100, 20))
        self.lbl_uid.setMaximumSize(QtCore.QSize(200, 25))
        self.lbl_uid.setObjectName("lbl_uid")
        self.gridLayout.addWidget(self.lbl_uid, 3, 0, 1, 1)
        self.lbl_output_folder = QtWidgets.QLabel(self.tlb_section_global)
        self.lbl_output_folder.setMinimumSize(QtCore.QSize(100, 20))
        self.lbl_output_folder.setMaximumSize(QtCore.QSize(200, 25))
        self.lbl_output_folder.setObjectName("lbl_output_folder")
        self.gridLayout.addWidget(self.lbl_output_folder, 1, 0, 1, 1)
        self.lbl_output_fileprefix = QtWidgets.QLabel(self.tlb_section_global)
        self.lbl_output_fileprefix.setMinimumSize(QtCore.QSize(100, 20))
        self.lbl_output_fileprefix.setMaximumSize(QtCore.QSize(200, 25))
        self.lbl_output_fileprefix.setObjectName("lbl_output_fileprefix")
        self.gridLayout.addWidget(self.lbl_output_fileprefix, 5, 0, 1, 1)
        self.int_md_uuid = QtWidgets.QSpinBox(self.tlb_section_global)
        self.int_md_uuid.setMinimumSize(QtCore.QSize(50, 20))
        self.int_md_uuid.setMaximumSize(QtCore.QSize(75, 35))
        self.int_md_uuid.setMaximum(8)
        self.int_md_uuid.setProperty("value", 5)
        self.int_md_uuid.setObjectName("int_md_uuid")
        self.gridLayout.addWidget(self.int_md_uuid, 3, 2, 1, 1)
        self.btn_directory_change = QtWidgets.QToolButton(self.tlb_section_global)
        self.btn_directory_change.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_directory_change.setText("...")
        self.btn_directory_change.setObjectName("btn_directory_change")
        self.gridLayout.addWidget(self.btn_directory_change, 1, 3, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/bars.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_settings.addItem(self.tlb_section_global, icon4, "")
        self.tlb_section_excel = QtWidgets.QWidget()
        self.tlb_section_excel.setGeometry(QtCore.QRect(0, 0, 424, 35))
        self.tlb_section_excel.setObjectName("tlb_section_excel")
        self.formLayout = QtWidgets.QFormLayout(self.tlb_section_excel)
        self.formLayout.setObjectName("formLayout")
        self.chb_xls_attributes = QtWidgets.QCheckBox(self.tlb_section_excel)
        self.chb_xls_attributes.setMinimumSize(QtCore.QSize(200, 0))
        self.chb_xls_attributes.setObjectName("chb_xls_attributes")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.chb_xls_attributes)
        self.chb_xls_stats = QtWidgets.QCheckBox(self.tlb_section_excel)
        self.chb_xls_stats.setMinimumSize(QtCore.QSize(200, 0))
        self.chb_xls_stats.setObjectName("chb_xls_stats")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chb_xls_stats)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/excel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_settings.addItem(self.tlb_section_excel, icon5, "Excel")
        self.tlb_section_word = QtWidgets.QWidget()
        self.tlb_section_word.setGeometry(QtCore.QRect(0, 0, 274, 43))
        self.tlb_section_word.setObjectName("tlb_section_word")
        self.formLayout_4 = QtWidgets.QFormLayout(self.tlb_section_word)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lbl_word_tpl = QtWidgets.QLabel(self.tlb_section_word)
        self.lbl_word_tpl.setMinimumSize(QtCore.QSize(100, 20))
        self.lbl_word_tpl.setMaximumSize(QtCore.QSize(150, 25))
        self.lbl_word_tpl.setObjectName("lbl_word_tpl")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_word_tpl)
        self.cbb_word_tpl = QtWidgets.QComboBox(self.tlb_section_word)
        self.cbb_word_tpl.setMinimumSize(QtCore.QSize(150, 25))
        self.cbb_word_tpl.setMaximumSize(QtCore.QSize(250, 35))
        self.cbb_word_tpl.setCurrentText("")
        self.cbb_word_tpl.setObjectName("cbb_word_tpl")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbb_word_tpl)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/word.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_settings.addItem(self.tlb_section_word, icon6, "Word")
        self.tlb_section_xml = QtWidgets.QWidget()
        self.tlb_section_xml.setGeometry(QtCore.QRect(0, 0, 190, 35))
        self.tlb_section_xml.setObjectName("tlb_section_xml")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tlb_section_xml)
        self.formLayout_2.setObjectName("formLayout_2")
        self.chb_xml_zip = QtWidgets.QCheckBox(self.tlb_section_xml)
        self.chb_xml_zip.setObjectName("chb_xml_zip")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.chb_xml_zip)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/xml.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_settings.addItem(self.tlb_section_xml, icon7, "XML")
        self.verticalLayout_4.addWidget(self.tlb_settings)
        self.verticalLayout_5.addWidget(self.grp_preferences)
        self.grp_auth = QtWidgets.QGroupBox(self.tab_settings)
        self.grp_auth.setMinimumSize(QtCore.QSize(550, 200))
        self.grp_auth.setMaximumSize(QtCore.QSize(600, 16777215))
        self.grp_auth.setObjectName("grp_auth")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.grp_auth)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbl_auth = QtWidgets.QLabel(self.grp_auth)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_auth.setFont(font)
        self.lbl_auth.setObjectName("lbl_auth")
        self.horizontalLayout_21.addWidget(self.lbl_auth)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem6)
        self.btn_change_user = QtWidgets.QPushButton(self.grp_auth)
        self.btn_change_user.setMinimumSize(QtCore.QSize(91, 24))
        self.btn_change_user.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_change_user.setIcon(icon8)
        self.btn_change_user.setObjectName("btn_change_user")
        self.horizontalLayout_21.addWidget(self.btn_change_user)
        self.gridLayout_10.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.txt_shares = QtWidgets.QTextBrowser(self.grp_auth)
        self.txt_shares.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txt_shares.setAutoFillBackground(True)
        self.txt_shares.setUndoRedoEnabled(False)
        self.txt_shares.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.txt_shares.setPlaceholderText("")
        self.txt_shares.setOpenExternalLinks(True)
        self.txt_shares.setOpenLinks(False)
        self.txt_shares.setObjectName("txt_shares")
        self.gridLayout_10.addWidget(self.txt_shares, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.grp_auth)
        self.grp_ressources = QtWidgets.QGroupBox(self.tab_settings)
        self.grp_ressources.setMinimumSize(QtCore.QSize(550, 150))
        self.grp_ressources.setMaximumSize(QtCore.QSize(600, 200))
        self.grp_ressources.setObjectName("grp_ressources")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.grp_ressources)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lbl_report = QtWidgets.QLabel(self.grp_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_report.setFont(font)
        self.lbl_report.setObjectName("lbl_report")
        self.horizontalLayout_24.addWidget(self.lbl_report)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem7)
        self.btn_log_dir = QtWidgets.QPushButton(self.grp_ressources)
        self.btn_log_dir.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_log_dir.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_log_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_log_dir.setAutoFillBackground(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/folder-open-o.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_log_dir.setIcon(icon9)
        self.btn_log_dir.setObjectName("btn_log_dir")
        self.horizontalLayout_24.addWidget(self.btn_log_dir)
        self.btn_report = QtWidgets.QPushButton(self.grp_ressources)
        self.btn_report.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_report.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_report.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_report.setAutoFillBackground(True)
        self.btn_report.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/bullhorn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_report.setIcon(icon10)
        self.btn_report.setObjectName("btn_report")
        self.horizontalLayout_24.addWidget(self.btn_report)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lbl_help = QtWidgets.QLabel(self.grp_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_help.setFont(font)
        self.lbl_help.setObjectName("lbl_help")
        self.horizontalLayout_23.addWidget(self.lbl_help)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem8)
        self.btn_help = QtWidgets.QPushButton(self.grp_ressources)
        self.btn_help.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_help.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_help.setAutoFillBackground(True)
        self.btn_help.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/question.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_help.setIcon(icon11)
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout_23.addWidget(self.btn_help)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lbl_credits = QtWidgets.QLabel(self.grp_ressources)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_credits.setFont(font)
        self.lbl_credits.setObjectName("lbl_credits")
        self.horizontalLayout_22.addWidget(self.lbl_credits)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.btn_credits = QtWidgets.QPushButton(self.grp_ressources)
        self.btn_credits.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_credits.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_credits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_credits.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_credits.setIcon(icon12)
        self.btn_credits.setObjectName("btn_credits")
        self.horizontalLayout_22.addWidget(self.btn_credits)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.gridLayout_11.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.grp_ressources)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/IsogeoToOffice/resources/settings/gear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs_IsogeoToOffice.addTab(self.tab_settings, icon13, "")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tabs_IsogeoToOffice)
        self.pgb_exports = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pgb_exports.sizePolicy().hasHeightForWidth())
        self.pgb_exports.setSizePolicy(sizePolicy)
        self.pgb_exports.setMinimumSize(QtCore.QSize(500, 30))
        self.pgb_exports.setMaximumSize(QtCore.QSize(1000, 40))
        self.pgb_exports.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pgb_exports.setAutoFillBackground(True)
        self.pgb_exports.setMaximum(100)
        self.pgb_exports.setProperty("value", 0)
        self.pgb_exports.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.pgb_exports.setTextVisible(True)
        self.pgb_exports.setInvertedAppearance(False)
        self.pgb_exports.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.pgb_exports.setFormat("%p%")
        self.pgb_exports.setObjectName("pgb_exports")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.pgb_exports)
        win_IsogeoToOffice.setCentralWidget(self.centralwidget)
        self.lbl_statusbar = QtWidgets.QStatusBar(win_IsogeoToOffice)
        self.lbl_statusbar.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.lbl_statusbar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_statusbar.setObjectName("lbl_statusbar")
        win_IsogeoToOffice.setStatusBar(self.lbl_statusbar)

        self.retranslateUi(win_IsogeoToOffice)
        self.tabs_IsogeoToOffice.setCurrentIndex(0)
        self.tlb_settings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(win_IsogeoToOffice)

    def retranslateUi(self, win_IsogeoToOffice):
        _translate = QtCore.QCoreApplication.translate
        self.grp_filters.setTitle(_translate("win_IsogeoToOffice", "Filters"))
        self.btn_reinit.setToolTip(_translate("win_IsogeoToOffice", "Reset search form"))
        self.lbl_share.setText(_translate("win_IsogeoToOffice", "Share"))
        self.lbl_owner.setText(_translate("win_IsogeoToOffice", "Metadata Owner"))
        self.lbl_type.setText(_translate("win_IsogeoToOffice", "Resource type"))
        self.lbl_keyword.setText(_translate("win_IsogeoToOffice", "Keyword"))
        self.grp_formats.setTitle(_translate("win_IsogeoToOffice", "Output formats"))
        self.btn_launch_export.setToolTip(_translate("win_IsogeoToOffice", "Launch export"))
        self.btn_launch_export.setText(_translate("win_IsogeoToOffice", "Launch export"))
        self.tabs_IsogeoToOffice.setTabText(self.tabs_IsogeoToOffice.indexOf(self.tab_export), _translate("win_IsogeoToOffice", "Export"))
        self.grp_preferences.setTitle(_translate("win_IsogeoToOffice", "Export settings"))
        self.lbl_timestamp.setText(_translate("win_IsogeoToOffice", "Display Timestamp:"))
        self.cbb_timestamp.setToolTip(_translate("win_IsogeoToOffice", "Add date or datetime to output filenames"))
        self.cbb_timestamp.setItemText(0, _translate("win_IsogeoToOffice", "No date (overwrite)"))
        self.cbb_timestamp.setItemText(1, _translate("win_IsogeoToOffice", "Day"))
        self.cbb_timestamp.setItemText(2, _translate("win_IsogeoToOffice", "Datetime"))
        self.lbl_output_folder_value.setToolTip(_translate("win_IsogeoToOffice", "Folder to store exported files"))
        self.lbl_output_folder_value.setText(_translate("win_IsogeoToOffice", "Output"))
        self.txt_output_fileprefix.setToolTip(_translate("win_IsogeoToOffice", "Custom output filename prefix"))
        self.txt_output_fileprefix.setText(_translate("win_IsogeoToOffice", "IsogeoToOffice"))
        self.txt_output_fileprefix.setPlaceholderText(_translate("win_IsogeoToOffice", "IsogeoToOffice"))
        self.lbl_uid.setText(_translate("win_IsogeoToOffice", "Length of metadata UUID:"))
        self.lbl_output_folder.setText(_translate("win_IsogeoToOffice", "Output repository:"))
        self.lbl_output_fileprefix.setText(_translate("win_IsogeoToOffice", "Output fileprefix:"))
        self.int_md_uuid.setToolTip(_translate("win_IsogeoToOffice", "Useful to avoid name conflicts"))
        self.int_md_uuid.setSuffix(_translate("win_IsogeoToOffice", " chars"))
        self.tlb_settings.setItemText(self.tlb_settings.indexOf(self.tlb_section_global), _translate("win_IsogeoToOffice", "Location and naming rules"))
        self.chb_xls_attributes.setToolTip(_translate("win_IsogeoToOffice", "Add a sheet to the output workbook about features attributes"))
        self.chb_xls_attributes.setText(_translate("win_IsogeoToOffice", "Features attributes analysis"))
        self.chb_xls_stats.setToolTip(_translate("win_IsogeoToOffice", "Add a sheet to the the output workbook with some metrics"))
        self.chb_xls_stats.setText(_translate("win_IsogeoToOffice", "Cataloguing dashboard"))
        self.lbl_word_tpl.setText(_translate("win_IsogeoToOffice", "Template to apply:"))
        self.cbb_word_tpl.setToolTip(_translate("win_IsogeoToOffice", "Word template to apply to the exported metadata"))
        self.chb_xml_zip.setToolTip(_translate("win_IsogeoToOffice", "Export metadata in XML ISO 19139"))
        self.chb_xml_zip.setText(_translate("win_IsogeoToOffice", "Pack all XML in one zip archive"))
        self.grp_auth.setTitle(_translate("win_IsogeoToOffice", "Authentication settings"))
        self.lbl_auth.setText(_translate("win_IsogeoToOffice", "Set application authentication:"))
        self.btn_change_user.setToolTip(_translate("win_IsogeoToOffice", "Change authentication settings"))
        self.txt_shares.setToolTip(_translate("win_IsogeoToOffice", "Application properties"))
        self.txt_shares.setHtml(_translate("win_IsogeoToOffice", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.grp_ressources.setTitle(_translate("win_IsogeoToOffice", "Resources"))
        self.lbl_report.setText(_translate("win_IsogeoToOffice", "Report an issue on the bug tracker"))
        self.btn_log_dir.setToolTip(_translate("win_IsogeoToOffice", "Get the log file: \"log_isogeo_isogeo2office.log\""))
        self.btn_log_dir.setText(_translate("win_IsogeoToOffice", "LOG File"))
        self.lbl_help.setText(_translate("win_IsogeoToOffice", "Open online application help"))
        self.btn_help.setToolTip(_translate("win_IsogeoToOffice", "Open online help in default browser"))
        self.lbl_credits.setText(_translate("win_IsogeoToOffice", "Open application credits"))
        self.btn_credits.setToolTip(_translate("win_IsogeoToOffice", "Open credits popup"))
        self.tabs_IsogeoToOffice.setTabText(self.tabs_IsogeoToOffice.indexOf(self.tab_settings), _translate("win_IsogeoToOffice", "Settings"))
        self.lbl_statusbar.setToolTip(_translate("win_IsogeoToOffice", "Status"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_IsogeoToOffice = QtWidgets.QMainWindow()
    ui = Ui_win_IsogeoToOffice()
    ui.setupUi(win_IsogeoToOffice)
    win_IsogeoToOffice.show()
    sys.exit(app.exec_())

